/**
 * Deterministic correspondence table, version `correspondence/v1`.
 *
 * GENERATED by `scripts/build-correspondence.ts`. Do not hand-edit: regenerate.
 *
 * Every one of the 170 vocabulary words reaches a concept, a planet, a kamea
 * square, a set of codex traditions, a candidate mark set and the composition
 * parameters the painter would apply. Every edge is a join between two authored
 * fields — the painter's own stamp and character pools against the codex rows,
 * and the codex rows against the 50 locked `geometry/v2` mark ids. No
 * association was invented; where no join exists the gap is recorded with the
 * prediction of what binding it anyway would change.
 *
 * Measured, not estimated:
 *   159 of 170 words reach at least one mark
 *   18 of 19 concepts reach at least one mark
 *   33 of 50 marks are reachable from some concept
 *   8 of 13 codex traditions are reached by some brush
 *   7 of 8 brushes map to a tradition; 1 is unmapped, with a reason
 */

import type { GlyphGeometryId } from "@studio137/plate-core";

export const CORRESPONDENCE_VERSION = "correspondence/v1";
/** The joins are authored; which mark a concept should *prefer* is not yet canon. */
export const CORRESPONDENCE_IS_PROVISIONAL = true;

/** Source of the correspondence, for anyone auditing an edge. */
export const CORRESPONDENCE_SOURCES = Object.freeze({
  painter: "assets/symbolpaintermk137.html",
  codex: "assets/codexdata.ts",
  geometry: "geometry/v2",
} as const);

export type TraditionKey = "adk" | "alch" | "ang" | "astro" | "chaos" | "egy" | "geo" | "goe" | "herm" | "ich" | "kab" | "rune" | "vod";
export type PlanetKey = "jupiter" | "luna" | "mars" | "mercury" | "saturn" | "sol" | "venus";
export type BrushKey = "alchemy" | "astro" | "geometry" | "hebrew" | "hiero" | "runic" | "sigil" | "trigram";
export type ModeKey = "attractor" | "chaos" | "cymatic" | "haring" | "lattice" | "mandelbrot" | "metatron" | "organic" | "phyllotaxis";
export type ArchKey = "emblem" | "hero" | "mandala" | "none";
export type PaletteKey = "blueprint" | "bone" | "haring" | "phosphor" | "spectrum" | "voidp";

/** A magic square, row-major, exactly as the painter stores it. */
export type BrushBinding = Readonly<{
  brush: BrushKey;
  label: string;
  /** The equality that produced every tradition below. */
  rule: string;
  traditions: readonly TraditionKey[];
  /** One line per joined token: what matched what. */
  evidence: readonly string[];
  /** Tokens in this brush's pool that no codex row matches, and what forcing them would change. */
  unresolved: readonly Readonly<{ token: string; reason: string }>[];
}>;

export type MarkBinding = Readonly<{
  mark: GlyphGeometryId;
  /** The mark id with its `mark-` prefix removed — the draw-function name. */
  stem: string;
  tradition: TraditionKey | null;
  via: "codex-id" | "codex-name" | "unbound";
  /** Empty for the ordinary id-join; a full account for anything else. */
  note: string;
}>;

export type ConceptCorrespondence = Readonly<{
  concept: string;
  planet: PlanetKey;
  /**
   * Which square this concept is walked on — a name, never the square itself.
   * `@studio137/walk-engine` owns the seven kamea and verifies them magic at
   * load. This module carried a second copy until it was removed: the grids were
   * identical, but two copies of a magic square is two answers to where a letter
   * lands, and the day they drift the walk and the legend disagree with no error
   * anywhere. House rule 1.
   */
  kamea: PlanetKey;
  brushes: readonly BrushKey[];
  traditions: readonly TraditionKey[];
  /** Marks reachable from this concept's traditions. Sorted; may be empty. */
  markCandidates: readonly GlyphGeometryId[];
  composition: Readonly<{
    mode: ModeKey;
    arch: ArchKey;
    palette: PaletteKey;
    fold: number;
    /** The ritual words the painter would sigilise for this concept. */
    words: readonly string[];
  }>;
  /** The vocabulary words that route here. Sorted. */
  words: readonly string[];
  /** Brushes on this concept whose every tradition has zero drawn marks. */
  brushesReachingNoMark: readonly BrushKey[];
}>;

export type WordCorrespondence = Readonly<{ word: string; concept: string }>;

/** The 13 codex traditions: key → [label, css custom-property]. */
export const TRADITION_LABELS: Readonly<Record<TraditionKey, readonly [string, string]>> = Object.freeze({
  adk: Object.freeze(["Adinkra (Akan)", "--adk"] as const),
  alch: Object.freeze(["Alchemy", "--alch"] as const),
  ang: Object.freeze(["Angelic & Theurgic", "--ang"] as const),
  astro: Object.freeze(["Planetary & Astrological", "--astro"] as const),
  chaos: Object.freeze(["Chaos & Modern", "--chaos"] as const),
  egy: Object.freeze(["Egyptian", "--egy"] as const),
  geo: Object.freeze(["Sacred Geometry", "--geo"] as const),
  goe: Object.freeze(["Goetic & Infernal", "--goe"] as const),
  herm: Object.freeze(["Hermetic & Universal", "--herm"] as const),
  ich: Object.freeze(["I Ching & Taoist", "--ich"] as const),
  kab: Object.freeze(["Kabbalah & Hebrew", "--kab"] as const),
  rune: Object.freeze(["Runic & Norse", "--rune"] as const),
  vod: Object.freeze(["Vodou Veve", "--vod"] as const),
});

/**
 * brush → tradition. Derived from `pickStamp()` in the painter: what each brush
 * actually draws, matched against the codex by exact string equality.
 */
export const BRUSH_BINDINGS: readonly BrushBinding[] = Object.freeze([
  Object.freeze({
    brush: "alchemy",
    label: "Alchemy",
    rule: "GLYPHS[brush].ch character === codex `g`",
    traditions: Object.freeze(["alch", "astro"] as const),
    evidence: Object.freeze([
      "GLYPHS.alchemy.ch \"☉\" === codex g → alch,astro",
      "GLYPHS.alchemy.ch \"☽\" === codex g → alch,astro",
      "GLYPHS.alchemy.ch \"☿\" === codex g → astro",
      "GLYPHS.alchemy.ch \"♀\" === codex g → alch,astro",
      "GLYPHS.alchemy.ch \"♂\" === codex g → alch,astro",
      "GLYPHS.alchemy.ch \"♃\" === codex g → alch,astro",
      "GLYPHS.alchemy.ch \"♄\" === codex g → alch,astro",
      "GLYPHS.alchemy.ch \"🜀\" === codex g → alch",
      "GLYPHS.alchemy.ch \"🜁\" === codex g → alch",
      "GLYPHS.alchemy.ch \"🜂\" === codex g → alch",
      "GLYPHS.alchemy.ch \"🜃\" === codex g → alch",
      "GLYPHS.alchemy.ch \"🜄\" === codex g → alch",
      "GLYPHS.alchemy.ch \"🜍\" === codex g → alch",
      "GLYPHS.alchemy.ch \"🜔\" === codex g → alch",
      "GLYPHS.alchemy.ch \"🜖\" === codex g → alch",
    ]),
    unresolved: Object.freeze([
      Object.freeze({ token: "🜊", reason: "the painter draws \"🜊\" but no codex row carries g === \"🜊\". PREDICTION IF FLIPPED: hand it to `alchemy`'s majority tradition \"alch\" and nothing measurable moves — 14 other characters in this pool already carry it, so no concept's candidate set changes. What changes is that 4 of this brush's 19 characters would be asserted rather than matched, and the same licence applied to a pool whose unmatched character belongs elsewhere would introduce a tradition no matched character supports." }),
      Object.freeze({ token: "🜋", reason: "the painter draws \"🜋\" but no codex row carries g === \"🜋\". PREDICTION IF FLIPPED: hand it to `alchemy`'s majority tradition \"alch\" and nothing measurable moves — 14 other characters in this pool already carry it, so no concept's candidate set changes. What changes is that 4 of this brush's 19 characters would be asserted rather than matched, and the same licence applied to a pool whose unmatched character belongs elsewhere would introduce a tradition no matched character supports." }),
      Object.freeze({ token: "🜐", reason: "the painter draws \"🜐\" but no codex row carries g === \"🜐\". PREDICTION IF FLIPPED: hand it to `alchemy`'s majority tradition \"alch\" and nothing measurable moves — 14 other characters in this pool already carry it, so no concept's candidate set changes. What changes is that 4 of this brush's 19 characters would be asserted rather than matched, and the same licence applied to a pool whose unmatched character belongs elsewhere would introduce a tradition no matched character supports." }),
      Object.freeze({ token: "🜛", reason: "the painter draws \"🜛\" but no codex row carries g === \"🜛\". PREDICTION IF FLIPPED: hand it to `alchemy`'s majority tradition \"alch\" and nothing measurable moves — 14 other characters in this pool already carry it, so no concept's candidate set changes. What changes is that 4 of this brush's 19 characters would be asserted rather than matched, and the same licence applied to a pool whose unmatched character belongs elsewhere would introduce a tradition no matched character supports." }),
    ]),
  }),
  Object.freeze({
    brush: "astro",
    label: "Astro",
    rule: "GLYPHS[brush].ch character === codex `g`",
    traditions: Object.freeze(["alch", "astro"] as const),
    evidence: Object.freeze([
      "GLYPHS.astro.ch \"☉\" === codex g → alch,astro",
      "GLYPHS.astro.ch \"☽\" === codex g → alch,astro",
      "GLYPHS.astro.ch \"☿\" === codex g → astro",
      "GLYPHS.astro.ch \"♀\" === codex g → alch,astro",
      "GLYPHS.astro.ch \"♂\" === codex g → alch,astro",
      "GLYPHS.astro.ch \"♃\" === codex g → alch,astro",
      "GLYPHS.astro.ch \"♄\" === codex g → alch,astro",
      "GLYPHS.astro.ch \"♅\" === codex g → astro",
      "GLYPHS.astro.ch \"♆\" === codex g → astro",
      "GLYPHS.astro.ch \"♇\" === codex g → astro",
      "GLYPHS.astro.ch \"♈\" === codex g → astro",
      "GLYPHS.astro.ch \"♉\" === codex g → astro",
      "GLYPHS.astro.ch \"♊\" === codex g → astro",
      "GLYPHS.astro.ch \"♋\" === codex g → astro",
      "GLYPHS.astro.ch \"♌\" === codex g → astro",
      "GLYPHS.astro.ch \"♍\" === codex g → astro",
      "GLYPHS.astro.ch \"♎\" === codex g → astro",
      "GLYPHS.astro.ch \"♏\" === codex g → astro",
      "GLYPHS.astro.ch \"♐\" === codex g → astro",
      "GLYPHS.astro.ch \"♑\" === codex g → astro",
      "GLYPHS.astro.ch \"♒\" === codex g → astro",
      "GLYPHS.astro.ch \"♓\" === codex g → astro",
    ]),
    unresolved: Object.freeze([]),
  }),
  Object.freeze({
    brush: "geometry",
    label: "Geometry",
    rule: "GEO stamp key === codex `id`, else === norm(codex `n`)",
    traditions: Object.freeze(["egy", "geo", "herm", "rune"] as const),
    evidence: Object.freeze([
      "GEO.ankh === norm(codex n \"Ankh\") → egy",
      "GEO.flower === codex id \"flower\" → geo",
      "GEO.hexagram === codex id \"hexagram\" → geo",
      "GEO.merkaba === codex id \"merkaba\" → geo",
      "GEO.metatron === codex id \"metatron\" → geo",
      "GEO.pentagram === codex id \"pentagram\" → geo",
      "GEO.seed === codex id \"seed\" → geo",
      "GEO.triquetra === codex id \"triquetra\" → herm",
      "GEO.triskele === codex id \"triskele\" → herm",
      "GEO.valknut === codex id \"valknut\" → rune",
      "GEO.vegvisir === codex id \"vegvisir\" → rune",
      "GEO.vesica === codex id \"vesica\" → geo",
    ]),
    unresolved: Object.freeze([
      Object.freeze({ token: "eye", reason: "no codex row has id === \"eye\" and none has norm(n) === \"eye\"; the nearest ids by substring are \"eyehorus\", \"eyeprov\". PREDICTION IF FLIPPED: bind GEO.eye to \"eyehorus\" because one id contains the other and nothing measurable moves — the brush already reaches \"egy\" through 1 exactly-matched stamp (ankh), so no concept gains or loses a candidate. Note that 2 ids contain or are contained by \"eye\" (\"eyehorus\", \"eyeprov\"), so the choice among them would be the binder's, not the data's. What changes is that the table would then hold one edge asserted by a substring instead of an equality, and the next such case — where the tradition is new — would have a precedent." }),
      Object.freeze({ token: "monad", reason: "no codex row has id === \"monad\" and none has norm(n) === \"monad\". PREDICTION IF FLIPPED: bind GEO.monad to a row chosen by what the name suggests and the geometry brush would gain a tradition from a reading of English — the one kind of edge this table refuses." }),
      Object.freeze({ token: "spiral", reason: "no codex row has id === \"spiral\" and none has norm(n) === \"spiral\"; the nearest ids by substring are \"goldenspiral\". PREDICTION IF FLIPPED: bind GEO.spiral to \"goldenspiral\" because one id contains the other and nothing measurable moves — the brush already reaches \"geo\" through 7 exactly-matched stamps (flower, hexagram, merkaba, metatron, pentagram, seed, vesica), so no concept gains or loses a candidate. What changes is that the table would then hold one edge asserted by a substring instead of an equality, and the next such case — where the tradition is new — would have a precedent." }),
      Object.freeze({ token: "unicursal", reason: "no codex row has id === \"unicursal\" and none has norm(n) === \"unicursal\"; the nearest ids by substring are \"unicursalhex\", \"sa\". PREDICTION IF FLIPPED: bind GEO.unicursal to \"unicursalhex\" because one id contains the other and nothing measurable moves — the brush already reaches \"herm\" through 2 exactly-matched stamps (triquetra, triskele), so no concept gains or loses a candidate. Note that 2 ids contain or are contained by \"unicursal\" (\"unicursalhex\", \"sa\"), so the choice among them would be the binder's, not the data's. What changes is that the table would then hold one edge asserted by a substring instead of an equality, and the next such case — where the tradition is new — would have a precedent." }),
    ]),
  }),
  Object.freeze({
    brush: "hebrew",
    label: "Hebrew",
    rule: "GLYPHS[brush].ch character === codex `g`",
    traditions: Object.freeze(["kab"] as const),
    evidence: Object.freeze([
      "GLYPHS.hebrew.ch \"א\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ב\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ג\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ד\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ה\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ו\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ז\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ח\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ט\" === codex g → kab",
      "GLYPHS.hebrew.ch \"י\" === codex g → kab",
      "GLYPHS.hebrew.ch \"כ\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ל\" === codex g → kab",
      "GLYPHS.hebrew.ch \"מ\" === codex g → kab",
      "GLYPHS.hebrew.ch \"נ\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ס\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ע\" === codex g → kab",
      "GLYPHS.hebrew.ch \"פ\" === codex g → kab",
      "GLYPHS.hebrew.ch \"צ\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ק\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ר\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ש\" === codex g → kab",
      "GLYPHS.hebrew.ch \"ת\" === codex g → kab",
    ]),
    unresolved: Object.freeze([]),
  }),
  Object.freeze({
    brush: "hiero",
    label: "Hiero",
    rule: "GLYPHS[brush].ch character === codex `g`",
    traditions: Object.freeze(["egy"] as const),
    evidence: Object.freeze([
      "GLYPHS.hiero.ch \"𓁹\" === codex g → egy",
      "GLYPHS.hiero.ch \"𓄤\" === codex g → egy",
      "GLYPHS.hiero.ch \"𓆄\" === codex g → egy",
      "GLYPHS.hiero.ch \"𓆣\" === codex g → egy",
      "GLYPHS.hiero.ch \"𓇳\" === codex g → egy",
      "GLYPHS.hiero.ch \"𓊽\" === codex g → egy",
      "GLYPHS.hiero.ch \"𓌀\" === codex g → egy",
    ]),
    unresolved: Object.freeze([
      Object.freeze({ token: "𓂀", reason: "the painter draws \"𓂀\" but no codex row carries g === \"𓂀\". PREDICTION IF FLIPPED: hand it to `hiero`'s majority tradition \"egy\" and nothing measurable moves — 7 other characters in this pool already carry it, so no concept's candidate set changes. What changes is that 5 of this brush's 12 characters would be asserted rather than matched, and the same licence applied to a pool whose unmatched character belongs elsewhere would introduce a tradition no matched character supports." }),
      Object.freeze({ token: "𓃭", reason: "the painter draws \"𓃭\" but no codex row carries g === \"𓃭\". PREDICTION IF FLIPPED: hand it to `hiero`'s majority tradition \"egy\" and nothing measurable moves — 7 other characters in this pool already carry it, so no concept's candidate set changes. What changes is that 5 of this brush's 12 characters would be asserted rather than matched, and the same licence applied to a pool whose unmatched character belongs elsewhere would introduce a tradition no matched character supports." }),
      Object.freeze({ token: "𓆃", reason: "the painter draws \"𓆃\" but no codex row carries g === \"𓆃\". PREDICTION IF FLIPPED: hand it to `hiero`'s majority tradition \"egy\" and nothing measurable moves — 7 other characters in this pool already carry it, so no concept's candidate set changes. What changes is that 5 of this brush's 12 characters would be asserted rather than matched, and the same licence applied to a pool whose unmatched character belongs elsewhere would introduce a tradition no matched character supports." }),
      Object.freeze({ token: "𓋹", reason: "the painter draws \"𓋹\" but no codex row carries g === \"𓋹\". PREDICTION IF FLIPPED: hand it to `hiero`'s majority tradition \"egy\" and nothing measurable moves — 7 other characters in this pool already carry it, so no concept's candidate set changes. What changes is that 5 of this brush's 12 characters would be asserted rather than matched, and the same licence applied to a pool whose unmatched character belongs elsewhere would introduce a tradition no matched character supports." }),
      Object.freeze({ token: "𓍝", reason: "the painter draws \"𓍝\" but no codex row carries g === \"𓍝\". PREDICTION IF FLIPPED: hand it to `hiero`'s majority tradition \"egy\" and nothing measurable moves — 7 other characters in this pool already carry it, so no concept's candidate set changes. What changes is that 5 of this brush's 12 characters would be asserted rather than matched, and the same licence applied to a pool whose unmatched character belongs elsewhere would introduce a tradition no matched character supports." }),
    ]),
  }),
  Object.freeze({
    brush: "runic",
    label: "Runic",
    rule: "GLYPHS[brush].ch character === codex `g`",
    traditions: Object.freeze(["rune"] as const),
    evidence: Object.freeze([
      "GLYPHS.runic.ch \"ᚠ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᚢ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᚦ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᚨ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᚱ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᚲ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᚷ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᚹ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᚺ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᚾ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛁ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛃ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛇ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛈ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛉ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛊ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛏ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛒ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛖ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛗ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛚ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛜ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛞ\" === codex g → rune",
      "GLYPHS.runic.ch \"ᛟ\" === codex g → rune",
    ]),
    unresolved: Object.freeze([]),
  }),
  Object.freeze({
    brush: "trigram",
    label: "Trigram",
    rule: "GLYPHS[brush].ch character === codex `g`",
    traditions: Object.freeze(["ich"] as const),
    evidence: Object.freeze([
      "GLYPHS.trigram.ch \"☰\" === codex g → ich",
      "GLYPHS.trigram.ch \"☱\" === codex g → ich",
      "GLYPHS.trigram.ch \"☲\" === codex g → ich",
      "GLYPHS.trigram.ch \"☳\" === codex g → ich",
      "GLYPHS.trigram.ch \"☴\" === codex g → ich",
      "GLYPHS.trigram.ch \"☵\" === codex g → ich",
      "GLYPHS.trigram.ch \"☶\" === codex g → ich",
      "GLYPHS.trigram.ch \"☷\" === codex g → ich",
    ]),
    unresolved: Object.freeze([]),
  }),
]);

/**
 * Brushes with no counterpart in the codex `T` table. Recorded, not forced.
 */
export const UNMAPPED_BRUSHES: readonly Readonly<{ brush: BrushKey; reason: string }>[] = Object.freeze([
  /**
   * pickStamp() defines `sigil` as sigilPath(word, planet): it walks the letters of a WORDS entry across one
   * of the 7 kamea and emits the resulting polyline. It selects no codex row, so it offers neither a
   * character to match against `g` nor a key to match against `id`, and the codex T table has no counterpart
   * for it. The nearest authored coincidence is that 5 of 22 WORDS entries (Agiel, Fire, Hagith, Sorath,
   * Zazel) equal the name-head of a codex row, across traditions "alch" and "ang" — but 5 of those 5 rows
   * have no mark in geometry/v2 at all: 4 are procedural `_seal_*` rows the extractor never drew, and 1
   * ("Fire") is a unicode row that shares a spelling with the painter's word rather than a designed
   * correspondence. PREDICTION IF FLIPPED: map `sigil` to "alch" + "ang" on that coincidence and the 3 marks
   * none of those rows named — "mark-ouroboros", "mark-sigillumdei", "mark-squaredcircle" — enter the
   * candidate sets of all 12 sigil-carrying concepts (air, chaos, descent, fire, lunar, mind, return,
   * shadow, spirit, threshold, union, water), taking mind from 0 candidates to 3 on the strength of a word
   * list.
   */
  Object.freeze({ brush: "sigil", reason: "pickStamp() defines `sigil` as sigilPath(word, planet): it walks the letters of a WORDS entry across one of the 7 kamea and emits the resulting polyline. It selects no codex row, so it offers neither a character to match against `g` nor a key to match against `id`, and the codex T table has no counterpart for it. The nearest authored coincidence is that 5 of 22 WORDS entries (Agiel, Fire, Hagith, Sorath, Zazel) equal the name-head of a codex row, across traditions \"alch\" and \"ang\" — but 5 of those 5 rows have no mark in geometry/v2 at all: 4 are procedural `_seal_*` rows the extractor never drew, and 1 (\"Fire\") is a unicode row that shares a spelling with the painter's word rather than a designed correspondence. PREDICTION IF FLIPPED: map `sigil` to \"alch\" + \"ang\" on that coincidence and the 3 marks none of those rows named — \"mark-ouroboros\", \"mark-sigillumdei\", \"mark-squaredcircle\" — enter the candidate sets of all 12 sigil-carrying concepts (air, chaos, descent, fire, lunar, mind, return, shadow, spirit, threshold, union, water), taking mind from 0 candidates to 3 on the strength of a word list." }),
]);

/**
 * mark → tradition, for all 50 locked marks. `via` says which authored field
 * carried the join; anything other than `codex-id` carries its full account.
 */
export const MARK_BINDINGS: readonly MarkBinding[] = Object.freeze([
  /**
   * assets/glyphdraws.ts defines a draw function `abraxas` and the extractor emitted mark-abraxas, but
   * assets/codexdata.ts has no row with id === "abraxas" and no row whose name normalises to "abraxas": the
   * glyph was drawn and never given a codex row, so it has no tradition and appears in no candidate set. The
   * only other authored occurrence of the string is "ABRAXAS" in the painter's WORDS pool, which the sigil
   * brush walks across a kamea — it synthesises a polyline from the letters and never draws this glyph. That
   * co-occurrence is recorded here and deliberately not used as an edge. PREDICTION IF FLIPPED: bind it on
   * that word and mark-abraxas becomes the only one of the 50 marks whose tradition came from a word list
   * rather than a codex row, and it enters the candidate set of all 12 sigil-carrying concepts.
   */
  Object.freeze({ mark: "mark-abraxas", stem: "abraxas", tradition: null, via: "unbound", note: "assets/glyphdraws.ts defines a draw function `abraxas` and the extractor emitted mark-abraxas, but assets/codexdata.ts has no row with id === \"abraxas\" and no row whose name normalises to \"abraxas\": the glyph was drawn and never given a codex row, so it has no tradition and appears in no candidate set. The only other authored occurrence of the string is \"ABRAXAS\" in the painter's WORDS pool, which the sigil brush walks across a kamea — it synthesises a polyline from the letters and never draws this glyph. That co-occurrence is recorded here and deliberately not used as an edge. PREDICTION IF FLIPPED: bind it on that word and mark-abraxas becomes the only one of the 50 marks whose tradition came from a word list rather than a codex row, and it enters the candidate set of all 12 sigil-carrying concepts." }),
  Object.freeze({ mark: "mark-adinkrahene", stem: "adinkrahene", tradition: "adk", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-aegishjalmur", stem: "aegishjalmur", tradition: "rune", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-akhet", stem: "akhet", tradition: "egy", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-akoma", stem: "akoma", tradition: "adk", via: "codex-id", note: "" }),
  /**
   * assets/glyphdraws.ts defines a draw function `ankh` and the extractor emitted mark-ankh, but
   * assets/codexdata.ts records it as U("Ankh", "egy", …, "☥") — a unicode row, and U() never sets an `id`.
   * The id-join that resolves the other 48 marks therefore finds nothing here. It binds on the name field
   * instead: norm("Ankh") === "ankh", an exact equality after case-folding and diacritic-stripping, not a
   * stem guess. PREDICTION IF FLIPPED: leave it unbound and tradition "egy" falls from 5 drawn marks to 4,
   * and each of the 10 concepts whose brushes reach "egy" loses exactly this one candidate.
   */
  Object.freeze({ mark: "mark-ankh", stem: "ankh", tradition: "egy", via: "codex-name", note: "assets/glyphdraws.ts defines a draw function `ankh` and the extractor emitted mark-ankh, but assets/codexdata.ts records it as U(\"Ankh\", \"egy\", …, \"☥\") — a unicode row, and U() never sets an `id`. The id-join that resolves the other 48 marks therefore finds nothing here. It binds on the name field instead: norm(\"Ankh\") === \"ankh\", an exact equality after case-folding and diacritic-stripping, not a stem guess. PREDICTION IF FLIPPED: leave it unbound and tradition \"egy\" falls from 5 drawn marks to 4, and each of the 10 concepts whose brushes reach \"egy\" loses exactly this one candidate." }),
  Object.freeze({ mark: "mark-baronsamedi", stem: "baronsamedi", tradition: "vod", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-borromean", stem: "borromean", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-chaossphere", stem: "chaossphere", tradition: "chaos", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-chaosstar", stem: "chaosstar", tradition: "chaos", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-damballa", stem: "damballa", tradition: "vod", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-dwennimmen", stem: "dwennimmen", tradition: "adk", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-eban", stem: "eban", tradition: "adk", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-erzulie", stem: "erzulie", tradition: "vod", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-eyehorus", stem: "eyehorus", tradition: "egy", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-eyeprov", stem: "eyeprov", tradition: "herm", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-flower", stem: "flower", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-fruit", stem: "fruit", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-goldenspiral", stem: "goldenspiral", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-gyenyame", stem: "gyenyame", tradition: "adk", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-hamsa", stem: "hamsa", tradition: "herm", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-hecate", stem: "hecate", tradition: "herm", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-hexagram", stem: "hexagram", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-legba", stem: "legba", tradition: "vod", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-leviathancross", stem: "leviathancross", tradition: "goe", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-lucifersigil", stem: "lucifersigil", tradition: "goe", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-merkaba", stem: "merkaba", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-metatron", stem: "metatron", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-monas", stem: "monas", tradition: "herm", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-nkyinkyim", stem: "nkyinkyim", tradition: "adk", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-ouroboros", stem: "ouroboros", tradition: "alch", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-pentagram", stem: "pentagram", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-rosecross", stem: "rosecross", tradition: "herm", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-sa", stem: "sa", tradition: "egy", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-sankofa", stem: "sankofa", tradition: "adk", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-seed", stem: "seed", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-sigillumdei", stem: "sigillumdei", tradition: "ang", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-squaredcircle", stem: "squaredcircle", tradition: "alch", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-sriyantra", stem: "sriyantra", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-tree", stem: "tree", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-triplemoon", stem: "triplemoon", tradition: "herm", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-triquetra", stem: "triquetra", tradition: "herm", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-triskele", stem: "triskele", tradition: "herm", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-tyet", stem: "tyet", tradition: "egy", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-unicursalhex", stem: "unicursalhex", tradition: "herm", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-valknut", stem: "valknut", tradition: "rune", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-vegvisir", stem: "vegvisir", tradition: "rune", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-veldismagn", stem: "veldismagn", tradition: "rune", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-vesica", stem: "vesica", tradition: "geo", via: "codex-id", note: "" }),
  Object.freeze({ mark: "mark-webofwyrd", stem: "webofwyrd", tradition: "rune", via: "codex-id", note: "" }),
]);

/** The 19 concepts, each with its complete chain. */
export const CONCEPT_CORRESPONDENCE: readonly ConceptCorrespondence[] = Object.freeze([
  Object.freeze({
    concept: "air",
    planet: "mercury",
    kamea: "mercury",
    brushes: Object.freeze(["astro", "sigil", "trigram"] as const),
    traditions: Object.freeze(["alch", "astro", "ich"] as const),
    markCandidates: Object.freeze(["mark-ouroboros", "mark-squaredcircle"] as const),
    composition: Object.freeze({
      mode: "lattice",
      arch: "emblem",
      palette: "phosphor",
      fold: 6,
      words: Object.freeze(["AETHER", "LUX"] as const),
    }),
    words: Object.freeze(["air", "breath", "cloud", "sky", "wind"] as const),
    brushesReachingNoMark: Object.freeze(["sigil", "trigram"] as const),
  }),
  Object.freeze({
    concept: "chaos",
    planet: "mars",
    kamea: "mars",
    brushes: Object.freeze(["alchemy", "runic", "sigil"] as const),
    traditions: Object.freeze(["alch", "astro", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-ouroboros", "mark-squaredcircle", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "chaos",
      arch: "none",
      palette: "spectrum",
      fold: 7,
      words: Object.freeze(["CHAOS", "NOX"] as const),
    }),
    words: Object.freeze(["abyss", "chaos", "dissolution", "entropy", "madness", "ruin", "storm"] as const),
    brushesReachingNoMark: Object.freeze(["sigil"] as const),
  }),
  Object.freeze({
    concept: "cosmos",
    planet: "jupiter",
    kamea: "jupiter",
    brushes: Object.freeze(["astro", "geometry"] as const),
    traditions: Object.freeze(["alch", "astro", "egy", "geo", "herm", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-akhet", "mark-ankh", "mark-borromean", "mark-eyehorus", "mark-eyeprov", "mark-flower", "mark-fruit", "mark-goldenspiral", "mark-hamsa", "mark-hecate", "mark-hexagram", "mark-merkaba", "mark-metatron", "mark-monas", "mark-ouroboros", "mark-pentagram", "mark-rosecross", "mark-sa", "mark-seed", "mark-squaredcircle", "mark-sriyantra", "mark-tree", "mark-triplemoon", "mark-triquetra", "mark-triskele", "mark-tyet", "mark-unicursalhex", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-vesica", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "phyllotaxis",
      arch: "mandala",
      palette: "phosphor",
      fold: 13,
      words: Object.freeze(["AETHER", "NUIT"] as const),
    }),
    words: Object.freeze(["cosmos", "galaxy", "heaven", "heavens", "infinite", "space", "star", "stars"] as const),
    brushesReachingNoMark: Object.freeze([] as const),
  }),
  Object.freeze({
    concept: "descent",
    planet: "saturn",
    kamea: "saturn",
    brushes: Object.freeze(["alchemy", "runic", "sigil"] as const),
    traditions: Object.freeze(["alch", "astro", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-ouroboros", "mark-squaredcircle", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "attractor",
      arch: "hero",
      palette: "voidp",
      fold: 9,
      words: Object.freeze(["NOX", "VOID", "ZAZEL"] as const),
    }),
    words: Object.freeze(["dark", "darkness", "death", "descent", "fall", "falling", "grief", "nigredo", "sink", "underworld"] as const),
    brushesReachingNoMark: Object.freeze(["sigil"] as const),
  }),
  Object.freeze({
    concept: "earth",
    planet: "saturn",
    kamea: "saturn",
    brushes: Object.freeze(["geometry", "runic"] as const),
    traditions: Object.freeze(["egy", "geo", "herm", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-akhet", "mark-ankh", "mark-borromean", "mark-eyehorus", "mark-eyeprov", "mark-flower", "mark-fruit", "mark-goldenspiral", "mark-hamsa", "mark-hecate", "mark-hexagram", "mark-merkaba", "mark-metatron", "mark-monas", "mark-pentagram", "mark-rosecross", "mark-sa", "mark-seed", "mark-sriyantra", "mark-tree", "mark-triplemoon", "mark-triquetra", "mark-triskele", "mark-tyet", "mark-unicursalhex", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-vesica", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "lattice",
      arch: "emblem",
      palette: "bone",
      fold: 4,
      words: Object.freeze(["KETHER", "VOID"] as const),
    }),
    words: Object.freeze(["body", "earth", "ground", "manifest", "mountain", "root", "roots", "soil", "stone"] as const),
    brushesReachingNoMark: Object.freeze([] as const),
  }),
  Object.freeze({
    concept: "fire",
    planet: "mars",
    kamea: "mars",
    brushes: Object.freeze(["alchemy", "geometry", "sigil"] as const),
    traditions: Object.freeze(["alch", "astro", "egy", "geo", "herm", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-akhet", "mark-ankh", "mark-borromean", "mark-eyehorus", "mark-eyeprov", "mark-flower", "mark-fruit", "mark-goldenspiral", "mark-hamsa", "mark-hecate", "mark-hexagram", "mark-merkaba", "mark-metatron", "mark-monas", "mark-ouroboros", "mark-pentagram", "mark-rosecross", "mark-sa", "mark-seed", "mark-squaredcircle", "mark-sriyantra", "mark-tree", "mark-triplemoon", "mark-triquetra", "mark-triskele", "mark-tyet", "mark-unicursalhex", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-vesica", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "chaos",
      arch: "hero",
      palette: "haring",
      fold: 5,
      words: Object.freeze(["FIRE", "LUX", "SORATH"] as const),
    }),
    words: Object.freeze(["burn", "burning", "ember", "fire", "flame", "flames", "forge", "heat", "passion"] as const),
    brushesReachingNoMark: Object.freeze(["sigil"] as const),
  }),
  Object.freeze({
    concept: "love",
    planet: "venus",
    kamea: "venus",
    brushes: Object.freeze(["alchemy", "astro"] as const),
    traditions: Object.freeze(["alch", "astro"] as const),
    markCandidates: Object.freeze(["mark-ouroboros", "mark-squaredcircle"] as const),
    composition: Object.freeze({
      mode: "organic",
      arch: "mandala",
      palette: "bone",
      fold: 7,
      words: Object.freeze(["BABALON", "HAGITH"] as const),
    }),
    words: Object.freeze(["beauty", "desire", "eros", "heart", "longing", "love", "lust", "venus"] as const),
    brushesReachingNoMark: Object.freeze([] as const),
  }),
  Object.freeze({
    concept: "lunar",
    planet: "luna",
    kamea: "luna",
    brushes: Object.freeze(["alchemy", "astro", "sigil"] as const),
    traditions: Object.freeze(["alch", "astro"] as const),
    markCandidates: Object.freeze(["mark-ouroboros", "mark-squaredcircle"] as const),
    composition: Object.freeze({
      mode: "cymatic",
      arch: "hero",
      palette: "blueprint",
      fold: 9,
      words: Object.freeze(["HAGITH", "LUNA", "NUIT"] as const),
    }),
    words: Object.freeze(["dream", "dreams", "luna", "lunar", "moon", "reflection", "silver", "tide", "tides"] as const),
    brushesReachingNoMark: Object.freeze(["sigil"] as const),
  }),
  Object.freeze({
    concept: "mind",
    planet: "mercury",
    kamea: "mercury",
    brushes: Object.freeze(["hebrew", "sigil", "trigram"] as const),
    traditions: Object.freeze(["ich", "kab"] as const),
    markCandidates: Object.freeze([] as const),
    composition: Object.freeze({
      mode: "lattice",
      arch: "emblem",
      palette: "phosphor",
      fold: 6,
      words: Object.freeze(["ALPHA", "LUX"] as const),
    }),
    words: Object.freeze(["hermes", "idea", "intellect", "magic", "magick", "mercury", "mind", "thought", "thoughts", "word", "words"] as const),
    brushesReachingNoMark: Object.freeze(["hebrew", "sigil", "trigram"] as const),
  }),
  Object.freeze({
    concept: "order",
    planet: "jupiter",
    kamea: "jupiter",
    brushes: Object.freeze(["geometry"] as const),
    traditions: Object.freeze(["egy", "geo", "herm", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-akhet", "mark-ankh", "mark-borromean", "mark-eyehorus", "mark-eyeprov", "mark-flower", "mark-fruit", "mark-goldenspiral", "mark-hamsa", "mark-hecate", "mark-hexagram", "mark-merkaba", "mark-metatron", "mark-monas", "mark-pentagram", "mark-rosecross", "mark-sa", "mark-seed", "mark-sriyantra", "mark-tree", "mark-triplemoon", "mark-triquetra", "mark-triskele", "mark-tyet", "mark-unicursalhex", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-vesica", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "lattice",
      arch: "mandala",
      palette: "blueprint",
      fold: 6,
      words: Object.freeze(["ALPHA", "KETHER"] as const),
    }),
    words: Object.freeze(["balance", "harmony", "law", "order", "pattern", "structure"] as const),
    brushesReachingNoMark: Object.freeze([] as const),
  }),
  Object.freeze({
    concept: "return",
    planet: "sol",
    kamea: "sol",
    brushes: Object.freeze(["alchemy", "astro", "sigil"] as const),
    traditions: Object.freeze(["alch", "astro"] as const),
    markCandidates: Object.freeze(["mark-ouroboros", "mark-squaredcircle"] as const),
    composition: Object.freeze({
      mode: "phyllotaxis",
      arch: "hero",
      palette: "bone",
      fold: 12,
      words: Object.freeze(["LUX", "SOL"] as const),
    }),
    words: Object.freeze(["ascend", "ascent", "awaken", "awakening", "clarity", "dawn", "illumination", "light", "rebirth", "renew", "renewal", "restore", "resurrect", "resurrection", "return", "rise"] as const),
    brushesReachingNoMark: Object.freeze(["sigil"] as const),
  }),
  Object.freeze({
    concept: "shadow",
    planet: "saturn",
    kamea: "saturn",
    brushes: Object.freeze(["runic", "sigil"] as const),
    traditions: Object.freeze(["rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "chaos",
      arch: "hero",
      palette: "voidp",
      fold: 7,
      words: Object.freeze(["NOX", "ZAZEL"] as const),
    }),
    words: Object.freeze(["hidden", "mystery", "occult", "secret", "shadow", "unconscious", "void"] as const),
    brushesReachingNoMark: Object.freeze(["sigil"] as const),
  }),
  Object.freeze({
    concept: "solar",
    planet: "sol",
    kamea: "sol",
    brushes: Object.freeze(["alchemy", "astro", "geometry"] as const),
    traditions: Object.freeze(["alch", "astro", "egy", "geo", "herm", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-akhet", "mark-ankh", "mark-borromean", "mark-eyehorus", "mark-eyeprov", "mark-flower", "mark-fruit", "mark-goldenspiral", "mark-hamsa", "mark-hecate", "mark-hexagram", "mark-merkaba", "mark-metatron", "mark-monas", "mark-ouroboros", "mark-pentagram", "mark-rosecross", "mark-sa", "mark-seed", "mark-squaredcircle", "mark-sriyantra", "mark-tree", "mark-triplemoon", "mark-triquetra", "mark-triskele", "mark-tyet", "mark-unicursalhex", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-vesica", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "phyllotaxis",
      arch: "mandala",
      palette: "bone",
      fold: 12,
      words: Object.freeze(["LUX", "SOL", "SORATH"] as const),
    }),
    words: Object.freeze(["crown", "glory", "gold", "golden", "king", "sol", "solar", "sun", "triumph", "victory"] as const),
    brushesReachingNoMark: Object.freeze([] as const),
  }),
  Object.freeze({
    concept: "spirit",
    planet: "sol",
    kamea: "sol",
    brushes: Object.freeze(["geometry", "hebrew", "sigil"] as const),
    traditions: Object.freeze(["egy", "geo", "herm", "kab", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-akhet", "mark-ankh", "mark-borromean", "mark-eyehorus", "mark-eyeprov", "mark-flower", "mark-fruit", "mark-goldenspiral", "mark-hamsa", "mark-hecate", "mark-hexagram", "mark-merkaba", "mark-metatron", "mark-monas", "mark-pentagram", "mark-rosecross", "mark-sa", "mark-seed", "mark-sriyantra", "mark-tree", "mark-triplemoon", "mark-triquetra", "mark-triskele", "mark-tyet", "mark-unicursalhex", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-vesica", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "metatron",
      arch: "hero",
      palette: "phosphor",
      fold: 8,
      words: Object.freeze(["AETHER", "KETHER"] as const),
    }),
    words: Object.freeze(["aether", "divine", "enlighten", "holy", "pneuma", "sacred", "soul", "spark", "spirit", "transcend"] as const),
    brushesReachingNoMark: Object.freeze(["hebrew", "sigil"] as const),
  }),
  Object.freeze({
    concept: "threshold",
    planet: "mercury",
    kamea: "mercury",
    brushes: Object.freeze(["geometry", "sigil"] as const),
    traditions: Object.freeze(["egy", "geo", "herm", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-akhet", "mark-ankh", "mark-borromean", "mark-eyehorus", "mark-eyeprov", "mark-flower", "mark-fruit", "mark-goldenspiral", "mark-hamsa", "mark-hecate", "mark-hexagram", "mark-merkaba", "mark-metatron", "mark-monas", "mark-pentagram", "mark-rosecross", "mark-sa", "mark-seed", "mark-sriyantra", "mark-tree", "mark-triplemoon", "mark-triquetra", "mark-triskele", "mark-tyet", "mark-unicursalhex", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-vesica", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "metatron",
      arch: "emblem",
      palette: "phosphor",
      fold: 8,
      words: Object.freeze(["ALPHA", "OMEGA"] as const),
    }),
    words: Object.freeze(["between", "crossing", "door", "gate", "gateway", "liminal", "portal", "threshold", "veil"] as const),
    brushesReachingNoMark: Object.freeze(["sigil"] as const),
  }),
  Object.freeze({
    concept: "time",
    planet: "saturn",
    kamea: "saturn",
    brushes: Object.freeze(["geometry", "runic"] as const),
    traditions: Object.freeze(["egy", "geo", "herm", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-akhet", "mark-ankh", "mark-borromean", "mark-eyehorus", "mark-eyeprov", "mark-flower", "mark-fruit", "mark-goldenspiral", "mark-hamsa", "mark-hecate", "mark-hexagram", "mark-merkaba", "mark-metatron", "mark-monas", "mark-pentagram", "mark-rosecross", "mark-sa", "mark-seed", "mark-sriyantra", "mark-tree", "mark-triplemoon", "mark-triquetra", "mark-triskele", "mark-tyet", "mark-unicursalhex", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-vesica", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "mandelbrot",
      arch: "mandala",
      palette: "voidp",
      fold: 9,
      words: Object.freeze(["NOX", "ZAZEL"] as const),
    }),
    words: Object.freeze(["age", "ages", "clock", "cycle", "cycles", "decay", "eternal", "kronos", "saturn", "time"] as const),
    brushesReachingNoMark: Object.freeze([] as const),
  }),
  Object.freeze({
    concept: "union",
    planet: "venus",
    kamea: "venus",
    brushes: Object.freeze(["alchemy", "geometry", "sigil"] as const),
    traditions: Object.freeze(["alch", "astro", "egy", "geo", "herm", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-akhet", "mark-ankh", "mark-borromean", "mark-eyehorus", "mark-eyeprov", "mark-flower", "mark-fruit", "mark-goldenspiral", "mark-hamsa", "mark-hecate", "mark-hexagram", "mark-merkaba", "mark-metatron", "mark-monas", "mark-ouroboros", "mark-pentagram", "mark-rosecross", "mark-sa", "mark-seed", "mark-squaredcircle", "mark-sriyantra", "mark-tree", "mark-triplemoon", "mark-triquetra", "mark-triskele", "mark-tyet", "mark-unicursalhex", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-vesica", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "metatron",
      arch: "emblem",
      palette: "bone",
      fold: 6,
      words: Object.freeze(["AZOTH", "BABALON"] as const),
    }),
    words: Object.freeze(["coniunctio", "join", "marriage", "merge", "one", "union", "wedding", "wholeness"] as const),
    brushesReachingNoMark: Object.freeze(["sigil"] as const),
  }),
  Object.freeze({
    concept: "war",
    planet: "mars",
    kamea: "mars",
    brushes: Object.freeze(["geometry", "runic"] as const),
    traditions: Object.freeze(["egy", "geo", "herm", "rune"] as const),
    markCandidates: Object.freeze(["mark-aegishjalmur", "mark-akhet", "mark-ankh", "mark-borromean", "mark-eyehorus", "mark-eyeprov", "mark-flower", "mark-fruit", "mark-goldenspiral", "mark-hamsa", "mark-hecate", "mark-hexagram", "mark-merkaba", "mark-metatron", "mark-monas", "mark-pentagram", "mark-rosecross", "mark-sa", "mark-seed", "mark-sriyantra", "mark-tree", "mark-triplemoon", "mark-triquetra", "mark-triskele", "mark-tyet", "mark-unicursalhex", "mark-valknut", "mark-vegvisir", "mark-veldismagn", "mark-vesica", "mark-webofwyrd"] as const),
    composition: Object.freeze({
      mode: "haring",
      arch: "emblem",
      palette: "haring",
      fold: 5,
      words: Object.freeze(["FIRE", "SORATH"] as const),
    }),
    words: Object.freeze(["battle", "blade", "conflict", "courage", "fight", "mars", "strife", "sword", "war"] as const),
    brushesReachingNoMark: Object.freeze([] as const),
  }),
  Object.freeze({
    concept: "water",
    planet: "luna",
    kamea: "luna",
    brushes: Object.freeze(["alchemy", "astro", "sigil"] as const),
    traditions: Object.freeze(["alch", "astro"] as const),
    markCandidates: Object.freeze(["mark-ouroboros", "mark-squaredcircle"] as const),
    composition: Object.freeze({
      mode: "cymatic",
      arch: "mandala",
      palette: "blueprint",
      fold: 8,
      words: Object.freeze(["AZOTH", "NUIT"] as const),
    }),
    words: Object.freeze(["dissolve", "flood", "flow", "liquid", "ocean", "rain", "river", "sea", "water"] as const),
    brushesReachingNoMark: Object.freeze(["sigil"] as const),
  }),
]);

/** All 170 vocabulary words, sorted, each with the concept `KEYS` routes it to. */
export const WORD_CORRESPONDENCE: readonly WordCorrespondence[] = Object.freeze([
  Object.freeze({ word: "abyss", concept: "chaos" }),
  Object.freeze({ word: "aether", concept: "spirit" }),
  Object.freeze({ word: "age", concept: "time" }),
  Object.freeze({ word: "ages", concept: "time" }),
  Object.freeze({ word: "air", concept: "air" }),
  Object.freeze({ word: "ascend", concept: "return" }),
  Object.freeze({ word: "ascent", concept: "return" }),
  Object.freeze({ word: "awaken", concept: "return" }),
  Object.freeze({ word: "awakening", concept: "return" }),
  Object.freeze({ word: "balance", concept: "order" }),
  Object.freeze({ word: "battle", concept: "war" }),
  Object.freeze({ word: "beauty", concept: "love" }),
  Object.freeze({ word: "between", concept: "threshold" }),
  Object.freeze({ word: "blade", concept: "war" }),
  Object.freeze({ word: "body", concept: "earth" }),
  Object.freeze({ word: "breath", concept: "air" }),
  Object.freeze({ word: "burn", concept: "fire" }),
  Object.freeze({ word: "burning", concept: "fire" }),
  Object.freeze({ word: "chaos", concept: "chaos" }),
  Object.freeze({ word: "clarity", concept: "return" }),
  Object.freeze({ word: "clock", concept: "time" }),
  Object.freeze({ word: "cloud", concept: "air" }),
  Object.freeze({ word: "conflict", concept: "war" }),
  Object.freeze({ word: "coniunctio", concept: "union" }),
  Object.freeze({ word: "cosmos", concept: "cosmos" }),
  Object.freeze({ word: "courage", concept: "war" }),
  Object.freeze({ word: "crossing", concept: "threshold" }),
  Object.freeze({ word: "crown", concept: "solar" }),
  Object.freeze({ word: "cycle", concept: "time" }),
  Object.freeze({ word: "cycles", concept: "time" }),
  Object.freeze({ word: "dark", concept: "descent" }),
  Object.freeze({ word: "darkness", concept: "descent" }),
  Object.freeze({ word: "dawn", concept: "return" }),
  Object.freeze({ word: "death", concept: "descent" }),
  Object.freeze({ word: "decay", concept: "time" }),
  Object.freeze({ word: "descent", concept: "descent" }),
  Object.freeze({ word: "desire", concept: "love" }),
  Object.freeze({ word: "dissolution", concept: "chaos" }),
  Object.freeze({ word: "dissolve", concept: "water" }),
  Object.freeze({ word: "divine", concept: "spirit" }),
  Object.freeze({ word: "door", concept: "threshold" }),
  Object.freeze({ word: "dream", concept: "lunar" }),
  Object.freeze({ word: "dreams", concept: "lunar" }),
  Object.freeze({ word: "earth", concept: "earth" }),
  Object.freeze({ word: "ember", concept: "fire" }),
  Object.freeze({ word: "enlighten", concept: "spirit" }),
  Object.freeze({ word: "entropy", concept: "chaos" }),
  Object.freeze({ word: "eros", concept: "love" }),
  Object.freeze({ word: "eternal", concept: "time" }),
  Object.freeze({ word: "fall", concept: "descent" }),
  Object.freeze({ word: "falling", concept: "descent" }),
  Object.freeze({ word: "fight", concept: "war" }),
  Object.freeze({ word: "fire", concept: "fire" }),
  Object.freeze({ word: "flame", concept: "fire" }),
  Object.freeze({ word: "flames", concept: "fire" }),
  Object.freeze({ word: "flood", concept: "water" }),
  Object.freeze({ word: "flow", concept: "water" }),
  Object.freeze({ word: "forge", concept: "fire" }),
  Object.freeze({ word: "galaxy", concept: "cosmos" }),
  Object.freeze({ word: "gate", concept: "threshold" }),
  Object.freeze({ word: "gateway", concept: "threshold" }),
  Object.freeze({ word: "glory", concept: "solar" }),
  Object.freeze({ word: "gold", concept: "solar" }),
  Object.freeze({ word: "golden", concept: "solar" }),
  Object.freeze({ word: "grief", concept: "descent" }),
  Object.freeze({ word: "ground", concept: "earth" }),
  Object.freeze({ word: "harmony", concept: "order" }),
  Object.freeze({ word: "heart", concept: "love" }),
  Object.freeze({ word: "heat", concept: "fire" }),
  Object.freeze({ word: "heaven", concept: "cosmos" }),
  Object.freeze({ word: "heavens", concept: "cosmos" }),
  Object.freeze({ word: "hermes", concept: "mind" }),
  Object.freeze({ word: "hidden", concept: "shadow" }),
  Object.freeze({ word: "holy", concept: "spirit" }),
  Object.freeze({ word: "idea", concept: "mind" }),
  Object.freeze({ word: "illumination", concept: "return" }),
  Object.freeze({ word: "infinite", concept: "cosmos" }),
  Object.freeze({ word: "intellect", concept: "mind" }),
  Object.freeze({ word: "join", concept: "union" }),
  Object.freeze({ word: "king", concept: "solar" }),
  Object.freeze({ word: "kronos", concept: "time" }),
  Object.freeze({ word: "law", concept: "order" }),
  Object.freeze({ word: "light", concept: "return" }),
  Object.freeze({ word: "liminal", concept: "threshold" }),
  Object.freeze({ word: "liquid", concept: "water" }),
  Object.freeze({ word: "longing", concept: "love" }),
  Object.freeze({ word: "love", concept: "love" }),
  Object.freeze({ word: "luna", concept: "lunar" }),
  Object.freeze({ word: "lunar", concept: "lunar" }),
  Object.freeze({ word: "lust", concept: "love" }),
  Object.freeze({ word: "madness", concept: "chaos" }),
  Object.freeze({ word: "magic", concept: "mind" }),
  Object.freeze({ word: "magick", concept: "mind" }),
  Object.freeze({ word: "manifest", concept: "earth" }),
  Object.freeze({ word: "marriage", concept: "union" }),
  Object.freeze({ word: "mars", concept: "war" }),
  Object.freeze({ word: "mercury", concept: "mind" }),
  Object.freeze({ word: "merge", concept: "union" }),
  Object.freeze({ word: "mind", concept: "mind" }),
  Object.freeze({ word: "moon", concept: "lunar" }),
  Object.freeze({ word: "mountain", concept: "earth" }),
  Object.freeze({ word: "mystery", concept: "shadow" }),
  Object.freeze({ word: "nigredo", concept: "descent" }),
  Object.freeze({ word: "occult", concept: "shadow" }),
  Object.freeze({ word: "ocean", concept: "water" }),
  Object.freeze({ word: "one", concept: "union" }),
  Object.freeze({ word: "order", concept: "order" }),
  Object.freeze({ word: "passion", concept: "fire" }),
  Object.freeze({ word: "pattern", concept: "order" }),
  Object.freeze({ word: "pneuma", concept: "spirit" }),
  Object.freeze({ word: "portal", concept: "threshold" }),
  Object.freeze({ word: "rain", concept: "water" }),
  Object.freeze({ word: "rebirth", concept: "return" }),
  Object.freeze({ word: "reflection", concept: "lunar" }),
  Object.freeze({ word: "renew", concept: "return" }),
  Object.freeze({ word: "renewal", concept: "return" }),
  Object.freeze({ word: "restore", concept: "return" }),
  Object.freeze({ word: "resurrect", concept: "return" }),
  Object.freeze({ word: "resurrection", concept: "return" }),
  Object.freeze({ word: "return", concept: "return" }),
  Object.freeze({ word: "rise", concept: "return" }),
  Object.freeze({ word: "river", concept: "water" }),
  Object.freeze({ word: "root", concept: "earth" }),
  Object.freeze({ word: "roots", concept: "earth" }),
  Object.freeze({ word: "ruin", concept: "chaos" }),
  Object.freeze({ word: "sacred", concept: "spirit" }),
  Object.freeze({ word: "saturn", concept: "time" }),
  Object.freeze({ word: "sea", concept: "water" }),
  Object.freeze({ word: "secret", concept: "shadow" }),
  Object.freeze({ word: "shadow", concept: "shadow" }),
  Object.freeze({ word: "silver", concept: "lunar" }),
  Object.freeze({ word: "sink", concept: "descent" }),
  Object.freeze({ word: "sky", concept: "air" }),
  Object.freeze({ word: "soil", concept: "earth" }),
  Object.freeze({ word: "sol", concept: "solar" }),
  Object.freeze({ word: "solar", concept: "solar" }),
  Object.freeze({ word: "soul", concept: "spirit" }),
  Object.freeze({ word: "space", concept: "cosmos" }),
  Object.freeze({ word: "spark", concept: "spirit" }),
  Object.freeze({ word: "spirit", concept: "spirit" }),
  Object.freeze({ word: "star", concept: "cosmos" }),
  Object.freeze({ word: "stars", concept: "cosmos" }),
  Object.freeze({ word: "stone", concept: "earth" }),
  Object.freeze({ word: "storm", concept: "chaos" }),
  Object.freeze({ word: "strife", concept: "war" }),
  Object.freeze({ word: "structure", concept: "order" }),
  Object.freeze({ word: "sun", concept: "solar" }),
  Object.freeze({ word: "sword", concept: "war" }),
  Object.freeze({ word: "thought", concept: "mind" }),
  Object.freeze({ word: "thoughts", concept: "mind" }),
  Object.freeze({ word: "threshold", concept: "threshold" }),
  Object.freeze({ word: "tide", concept: "lunar" }),
  Object.freeze({ word: "tides", concept: "lunar" }),
  Object.freeze({ word: "time", concept: "time" }),
  Object.freeze({ word: "transcend", concept: "spirit" }),
  Object.freeze({ word: "triumph", concept: "solar" }),
  Object.freeze({ word: "unconscious", concept: "shadow" }),
  Object.freeze({ word: "underworld", concept: "descent" }),
  Object.freeze({ word: "union", concept: "union" }),
  Object.freeze({ word: "veil", concept: "threshold" }),
  Object.freeze({ word: "venus", concept: "love" }),
  Object.freeze({ word: "victory", concept: "solar" }),
  Object.freeze({ word: "void", concept: "shadow" }),
  Object.freeze({ word: "war", concept: "war" }),
  Object.freeze({ word: "water", concept: "water" }),
  Object.freeze({ word: "wedding", concept: "union" }),
  Object.freeze({ word: "wholeness", concept: "union" }),
  Object.freeze({ word: "wind", concept: "air" }),
  Object.freeze({ word: "word", concept: "mind" }),
  Object.freeze({ word: "words", concept: "mind" }),
]);

/** Counted from the tables above at generation time. */
export const CORRESPONDENCE_COVERAGE = Object.freeze({
  words: 170,
  wordsReachingAMark: 159,
  wordsReachingNoMark: 11,
  wordsReachingNoMarkList: Object.freeze(["hermes", "idea", "intellect", "magic", "magick", "mercury", "mind", "thought", "thoughts", "word", "words"] as const),
  concepts: 19,
  conceptsReachingAMark: 18,
  conceptsReachingNoMark: 1,
  conceptsReachingNoMarkNames: Object.freeze(["mind"] as const),
  marksLocked: 50,
  marksBoundToATradition: 49,
  marksReachableFromAConcept: 33,
  marksReachableFromNoConcept: Object.freeze(["mark-abraxas", "mark-adinkrahene", "mark-akoma", "mark-baronsamedi", "mark-chaossphere", "mark-chaosstar", "mark-damballa", "mark-dwennimmen", "mark-eban", "mark-erzulie", "mark-gyenyame", "mark-legba", "mark-leviathancross", "mark-lucifersigil", "mark-nkyinkyim", "mark-sankofa", "mark-sigillumdei"] as const),
  traditionsInCodex: 13,
  traditionsReachedByABrush: 8,
  traditionsWithNoDrawnMark: Object.freeze(["astro", "ich", "kab"] as const),
  traditionsReachedByNoBrush: Object.freeze(["adk", "ang", "chaos", "goe", "vod"] as const),
  brushesDefined: 8,
  brushesMapped: 7,
  brushesUnmapped: 1,
  brushesUsedByNoConcept: Object.freeze(["hiero"] as const),
  conceptsPerPlanet: Object.freeze({
    jupiter: 2,
    luna: 2,
    mars: 3,
    mercury: 3,
    saturn: 4,
    sol: 3,
    venus: 2,
  } as const),
  marksPerTradition: Object.freeze({
    adk: 7,
    alch: 2,
    ang: 1,
    astro: 0,
    chaos: 2,
    egy: 5,
    geo: 12,
    goe: 2,
    herm: 9,
    ich: 0,
    kab: 0,
    rune: 5,
    vod: 4,
  } as const),
} as const);

const BY_WORD: ReadonlyMap<string, ConceptCorrespondence> = new Map(
  WORD_CORRESPONDENCE.flatMap((w) => {
    const c = CONCEPT_CORRESPONDENCE.find((x) => x.concept === w.concept);
    return c ? [[w.word, c] as const] : [];
  }),
);

/** Look a vocabulary word up. Case-insensitive, matching the painter's own lowercasing. */
export function correspondenceForWord(word: string): ConceptCorrespondence | undefined {
  return BY_WORD.get(word.toLowerCase());
}

/** Look a concept up by name. */
export function correspondenceForConcept(concept: string): ConceptCorrespondence | undefined {
  return CONCEPT_CORRESPONDENCE.find((c) => c.concept === concept);
}

