/**
 * Constructed numerals for dimension callouts, version `numerals/v1`.
 *
 * GENERATED by `scripts/build-numerals.ts`. Do not hand-edit: regenerate
 * instead, and remember that a released version is immutable — a redraw lands
 * as v2.
 *
 * WHY THIS EXISTS. The renderer structurally cannot emit `<text>`
 * (`packages/render-svg/src/xml.ts` has no text-node branch) and the geometry
 * extractor quarantines any mark that depends on one. A glyph resolved through
 * a system font is not authored geometry: a different machine with a different
 * font paints different ink, determinism is gone, and the version contract goes
 * with it. So the numerals a technical drawing needs are drawn the same way
 * every other mark here is drawn — as locked path data.
 *
 * COMPASS AND RULE. Every path is a word in `{M, L, A, Z}`: straight segments
 * and circular arcs, nothing else. There is no bezier in this file and no font
 * touched the pipeline that produced it. Each record carries the sentence its
 * construction was stated in.
 *
 * METRICS. Figure height 72 units, from a top of 14 to a baseline of 86,
 * built about the advance axis at x=50. Every stroked path in the set is
 * 7 units wide — one weight, one scriber, exponents included. The only filled
 * path in the set is the period's disc, which is filled so that a decimal point
 * cannot disappear under a renderer's butt caps.
 *
 * MONOSPACED. Every text-size glyph advances 100 units and every superscript
 * advances 62, so digits stack in a column and a superscript run stays on
 * its own even rhythm. The advance IS the viewBox width — a consumer lays the
 * set out by summing `viewBox[2]`, with no side-table of widths to drift.
 *
 * INK. `inkBounds` is measured by flattening the emitted path strings and
 * sampling them — arc bellies included, stroke width included — never from
 * endpoints or control points. Worst-case overflow past the declared viewBox
 * across the whole set is -6.5 units.
 */

import type { GlyphGeometryId } from "@studio137/plate-core";

import type { LockedPath } from "./types.js";

export const NUMERALS_V1_VERSION = "numerals/v1";

/** The one stroke weight of the set, in viewBox units. */
export const NUMERAL_STROKE_WIDTH = 7;

/** The metric frame every glyph was constructed on. */
export const NUMERAL_METRICS = Object.freeze({
  advance: 100,
  superscriptAdvance: 62,
  superscriptScale: 0.62,
  figureTop: 14,
  baseline: 86,
  figureHeight: 72,
  xHeightTop: 36,
  mathAxis: 50,
  strokeWidth: 7,
});

export type NumeralSource = Readonly<{
  id: GlyphGeometryId;
  /** The character this glyph sets. Present so a caller can build a string map. */
  character: string;
  /** How it was constructed, in one sentence. */
  construction: string;
  /** `[minX, minY, width, height]`. The width is also the advance. */
  viewBox: readonly [number, number, number, number];
  paths: readonly LockedPath[];
  /** Measured by sampling the flattened paths, stroke width included. */
  inkBounds: readonly [number, number, number, number];
}>;

const stroke = (d: string): LockedPath =>
  Object.freeze({ d, role: "stroke" as const, strokeWidth: NUMERAL_STROKE_WIDTH });
const fill = (d: string): LockedPath =>
  Object.freeze({ d, role: "fill" as const, strokeWidth: 0 });

const TEXT_VIEWBOX = Object.freeze([0, 0, 100, 100] as const);
const SUPERSCRIPT_VIEWBOX = Object.freeze([0, 0, 62, 100] as const);

export const NUMERALS_V1_SOURCE: readonly NumeralSource[] = Object.freeze([
  {
    id: "numeral-0",
    character: "0",
    construction: "four-centre oval, 50 x 72, with an interior slash",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M37.6323 19.1772 A17.3611 17.3611 0 0 1 62.3677 19.1772 A43.92 43.92 0 0 1 62.3677 80.8228 A17.3611 17.3611 0 0 1 37.6323 80.8228 A43.92 43.92 0 0 1 37.6323 19.1772 Z"),
      stroke("M41.5 62 L58.5 38"),
    ]),
    inkBounds: Object.freeze([21.5, 10.5, 78.5, 89.5] as const),
  },
  {
    id: "numeral-1",
    character: "1",
    construction: "stem, flag, foot serif",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M33 27 L50 14 L50 86"),
      stroke("M34 86 L66 86"),
    ]),
    inkBounds: Object.freeze([29.5, 10.5, 69.5, 89.5] as const),
  },
  {
    id: "numeral-2",
    character: "2",
    construction: "220° bowl, straight diagonal, base bar",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M30.6815 28.8236 A20 20 0 1 1 61.4715 50.383 L29 86 L73 86"),
    ]),
    inkBounds: Object.freeze([25.5, 10.5011, 76.5, 89.5] as const),
  },
  {
    id: "numeral-3",
    character: "3",
    construction: "two crossing circles, r18 over r21",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M33.0855 25.8436 A18 18 0 1 1 60.3493 46.7273 A21 21 0 1 1 30.2665 72.1824"),
    ]),
    inkBounds: Object.freeze([26.7665, 10.5011, 74.4982, 89.4962] as const),
  },
  {
    id: "numeral-4",
    character: "4",
    construction: "stem, diagonal, crossbar — one straightedge stroke",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M61 86 L61 14 L25 63 L75 63"),
    ]),
    inkBounds: Object.freeze([21.5, 10.5, 78.5, 89.5] as const),
  },
  {
    id: "numeral-5",
    character: "5",
    construction: "top bar, stem, 285° bowl",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M69 14 L28.2486 14 L28.2486 51.8572 A24 24 0 1 1 34.5731 80.3851"),
    ]),
    inkBounds: Object.freeze([24.7486, 10.5, 77.4986, 89.4928] as const),
  },
  {
    id: "numeral-6",
    character: "6",
    construction: "closed r23 bowl, spine arc struck tangent at nine o'clock",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M69 14 A49.5833 49.5833 0 0 0 27 63"),
      stroke("M27 63 A23 23 0 0 1 73 63 A23 23 0 0 1 27 63 Z"),
    ]),
    inkBounds: Object.freeze([23.5, 10.5, 76.5, 89.5] as const),
  },
  {
    id: "numeral-7",
    character: "7",
    construction: "top bar, diagonal, barred at mid-height",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M26 14 L74 14 L40 86"),
      stroke("M45.0556 52 L67.0556 52"),
    ]),
    inkBounds: Object.freeze([22.5, 10.5, 77.5, 89.5] as const),
  },
  {
    id: "numeral-8",
    character: "8",
    construction: "two tangent circles, r16 over r20",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M34 30 A16 16 0 0 1 66 30 A16 16 0 0 1 34 30 Z"),
      stroke("M30 66 A20 20 0 0 1 70 66 A20 20 0 0 1 30 66 Z"),
    ]),
    inkBounds: Object.freeze([26.5, 10.5, 73.5, 89.5] as const),
  },
  {
    id: "numeral-9",
    character: "9",
    construction: "the 6, rotated a half-turn about (50, 50)",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M31 86 A49.5833 49.5833 0 0 0 73 37"),
      stroke("M27 37 A23 23 0 0 1 73 37 A23 23 0 0 1 27 37 Z"),
    ]),
    inkBounds: Object.freeze([23.5, 10.5, 76.5, 89.5] as const),
  },
  {
    id: "numeral-plus",
    character: "+",
    construction: "two 40-unit rules crossing on the axis",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M30 50 L70 50"),
      stroke("M50 30 L50 70"),
    ]),
    inkBounds: Object.freeze([26.5, 26.5, 73.5, 73.5] as const),
  },
  {
    id: "numeral-minus",
    character: "−",
    construction: "the plus's horizontal rule, alone",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M30 50 L70 50"),
    ]),
    inkBounds: Object.freeze([26.5, 46.5, 73.5, 53.5] as const),
  },
  {
    id: "numeral-plusminus",
    character: "±",
    construction: "plus on a raised axis over a base bar",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M33 43 L67 43"),
      stroke("M50 26 L50 60"),
      stroke("M33 74 L67 74"),
    ]),
    inkBounds: Object.freeze([29.5, 22.5, 70.5, 77.5] as const),
  },
  {
    id: "numeral-multiply",
    character: "×",
    construction: "the plus at 45°, arms shortened for equal optical mass",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M36 36 L64 64"),
      stroke("M64 36 L36 64"),
    ]),
    inkBounds: Object.freeze([32.5, 32.5, 67.5, 67.5] as const),
  },
  {
    id: "numeral-period",
    character: ".",
    construction: "filled disc, r4, seated on the baseline ink line",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      fill("M46 85.5 A4 4 0 0 1 54 85.5 A4 4 0 0 1 46 85.5 Z"),
    ]),
    inkBounds: Object.freeze([46, 81.5, 54, 89.5] as const),
  },
  {
    id: "numeral-solidus",
    character: "/",
    construction: "single rule, overshooting the figure box",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M32 88 L68 12"),
    ]),
    inkBounds: Object.freeze([28.5, 8.5, 71.5, 91.5] as const),
  },
  {
    id: "numeral-paren-left",
    character: "(",
    construction: "arc on an 80-unit chord with a 16-unit sagitta",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M63 10 A43.7692 43.7692 0 0 0 63 90"),
    ]),
    inkBounds: Object.freeze([33.5, 6.5, 66.5, 93.5] as const),
  },
  {
    id: "numeral-paren-right",
    character: ")",
    construction: "the left parenthesis, reflected in the advance axis",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M37 10 A43.7692 43.7692 0 0 1 37 90"),
    ]),
    inkBounds: Object.freeze([33.5, 6.5, 66.5, 93.5] as const),
  },
  {
    id: "numeral-degree",
    character: "°",
    construction: "r7.5 ring at the figure top, 8-unit counter",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M42.5 25 A7.5 7.5 0 0 1 57.5 25 A7.5 7.5 0 0 1 42.5 25 Z"),
    ]),
    inkBounds: Object.freeze([39, 14, 61, 36] as const),
  },
  {
    id: "numeral-lower-m",
    character: "m",
    construction: "three stems on a 23 pitch, two half-circle arches",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M27 86 L27 47.5 A11.5 11.5 0 0 1 50 47.5 L50 86"),
      stroke("M50 47.5 A11.5 11.5 0 0 1 73 47.5 L73 86"),
    ]),
    inkBounds: Object.freeze([23.5, 32.5, 76.5, 89.5] as const),
  },
  {
    id: "numeral-cap-l",
    character: "L",
    construction: "stem and foot, centred on the advance",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M32 14 L32 86 L68 86"),
    ]),
    inkBounds: Object.freeze([28.5, 10.5, 71.5, 89.5] as const),
  },
  {
    id: "numeral-cap-s",
    character: "S",
    construction: "the 3, reflected in the advance axis",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M66.9145 25.8436 A18 18 0 1 0 39.6507 46.7273 A21 21 0 1 0 69.7335 72.1824"),
    ]),
    inkBounds: Object.freeze([25.5018, 10.5011, 73.2335, 89.4962] as const),
  },
  {
    id: "numeral-sup-0",
    character: "⁰",
    construction: "four-centre oval, 50 x 72, with an interior slash — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M23.332 18.2098 A10.7639 10.7639 0 0 1 38.668 18.2098 A27.2304 27.2304 0 0 1 38.668 56.4302 A10.7639 10.7639 0 0 1 23.332 56.4302 A27.2304 27.2304 0 0 1 23.332 18.2098 Z"),
      stroke("M25.73 44.76 L36.27 29.88"),
    ]),
    inkBounds: Object.freeze([11.9999, 11.4999, 50.0001, 63.1401] as const),
  },
  {
    id: "numeral-sup-1",
    character: "¹",
    construction: "stem, flag, foot serif — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M20.46 23.06 L31 15 L31 59.64"),
      stroke("M21.08 59.64 L40.92 59.64"),
    ]),
    inkBounds: Object.freeze([16.96, 11.5, 44.42, 63.14] as const),
  },
  {
    id: "numeral-sup-2",
    character: "²",
    construction: "220° bowl, straight diagonal, base bar — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M19.0225 24.1906 A12.4 12.4 0 1 1 38.1123 37.5575 L17.98 59.64 L45.26 59.64"),
    ]),
    inkBounds: Object.freeze([14.48, 11.5007, 48.76, 63.14] as const),
  },
  {
    id: "numeral-sup-3",
    character: "³",
    construction: "two crossing circles, r18 over r21 — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M20.513 22.3431 A11.16 11.16 0 1 1 37.4165 35.2909 A13.02 13.02 0 1 1 18.7652 51.0731"),
    ]),
    inkBounds: Object.freeze([15.2652, 11.5006, 47.5189, 63.1376] as const),
  },
  {
    id: "numeral-sup-4",
    character: "⁴",
    construction: "stem, diagonal, crossbar — one straightedge stroke — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M37.82 59.64 L37.82 15 L15.5 45.38 L46.5 45.38"),
    ]),
    inkBounds: Object.freeze([12, 11.5, 50, 63.14] as const),
  },
  {
    id: "numeral-sup-5",
    character: "⁵",
    construction: "top bar, stem, 285° bowl — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M42.78 15 L17.5141 15 L17.5141 38.4714 A14.88 14.88 0 1 1 21.4353 56.1587"),
    ]),
    inkBounds: Object.freeze([14.0141, 11.5, 49.3791, 63.1355] as const),
  },
  {
    id: "numeral-sup-6",
    character: "⁶",
    construction: "closed r23 bowl, spine arc struck tangent at nine o'clock — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M42.78 15 A30.7417 30.7417 0 0 0 16.74 45.38"),
      stroke("M16.74 45.38 A14.26 14.26 0 0 1 45.26 45.38 A14.26 14.26 0 0 1 16.74 45.38 Z"),
    ]),
    inkBounds: Object.freeze([13.24, 11.5, 48.76, 63.14] as const),
  },
  {
    id: "numeral-sup-7",
    character: "⁷",
    construction: "top bar, diagonal, barred at mid-height — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M16.12 15 L45.88 15 L24.8 59.64"),
      stroke("M27.9344 38.56 L41.5744 38.56"),
    ]),
    inkBounds: Object.freeze([12.62, 11.5, 49.38, 63.14] as const),
  },
  {
    id: "numeral-sup-8",
    character: "⁸",
    construction: "two tangent circles, r16 over r20 — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M21.08 24.92 A9.92 9.92 0 0 1 40.92 24.92 A9.92 9.92 0 0 1 21.08 24.92 Z"),
      stroke("M18.6 47.24 A12.4 12.4 0 0 1 43.4 47.24 A12.4 12.4 0 0 1 18.6 47.24 Z"),
    ]),
    inkBounds: Object.freeze([15.1, 11.5, 46.9, 63.14] as const),
  },
  {
    id: "numeral-sup-9",
    character: "⁹",
    construction: "the 6, rotated a half-turn about (50, 50) — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M19.22 59.64 A30.7417 30.7417 0 0 0 45.26 29.26"),
      stroke("M16.74 29.26 A14.26 14.26 0 0 1 45.26 29.26 A14.26 14.26 0 0 1 16.74 29.26 Z"),
    ]),
    inkBounds: Object.freeze([13.24, 11.5, 48.76, 63.14] as const),
  },
  {
    id: "numeral-sup-minus",
    character: "⁻",
    construction: "the plus's horizontal rule, alone — scaled 0.62 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M18.6 37.32 L43.4 37.32"),
    ]),
    inkBounds: Object.freeze([15.1, 33.82, 46.9, 40.82] as const),
  },
]);

/**
 * Character → glyph id. ASCII `-` is mapped alongside U+2212 MINUS SIGN so a
 * caller typing a plain hyphen still gets the set's minus rather than nothing.
 */
export const NUMERAL_BY_CHARACTER: Readonly<Record<string, GlyphGeometryId>> = Object.freeze({
  "0": "numeral-0",
  "1": "numeral-1",
  "2": "numeral-2",
  "3": "numeral-3",
  "4": "numeral-4",
  "5": "numeral-5",
  "6": "numeral-6",
  "7": "numeral-7",
  "8": "numeral-8",
  "9": "numeral-9",
  "+": "numeral-plus",
  "−": "numeral-minus",
  "±": "numeral-plusminus",
  "×": "numeral-multiply",
  ".": "numeral-period",
  "/": "numeral-solidus",
  "(": "numeral-paren-left",
  ")": "numeral-paren-right",
  "°": "numeral-degree",
  "m": "numeral-lower-m",
  "L": "numeral-cap-l",
  "S": "numeral-cap-s",
  "⁰": "numeral-sup-0",
  "¹": "numeral-sup-1",
  "²": "numeral-sup-2",
  "³": "numeral-sup-3",
  "⁴": "numeral-sup-4",
  "⁵": "numeral-sup-5",
  "⁶": "numeral-sup-6",
  "⁷": "numeral-sup-7",
  "⁸": "numeral-sup-8",
  "⁹": "numeral-sup-9",
  "⁻": "numeral-sup-minus",
  "-": "numeral-minus",
});
