/**
 * Constructed numerals for dimension callouts, version `numerals/v1`.
 *
 * GENERATED by `scripts/build-numerals.ts`. Do not hand-edit: regenerate
 * instead, and remember that a released version is immutable — a redraw lands
 * as v2.
 *
 * WHY THIS EXISTS. The renderer structurally cannot emit `<text>`
 * (`packages/render-svg/src/xml.ts` has no text-node branch) and the geometry
 * extractor quarantines any mark that depends on one. A glyph resolved through
 * a system font is not authored geometry: a different machine with a different
 * font paints different ink, determinism is gone, and the version contract goes
 * with it. So the numerals a technical drawing needs are drawn the same way
 * every other mark here is drawn — as locked path data.
 *
 * COMPASS AND RULE. Every path is a word in `{M, L, A, Z}`: straight segments
 * and circular arcs, nothing else. There is no bezier in this file and no font
 * touched the pipeline that produced it. Each record carries the sentence its
 * construction was stated in.
 *
 * METRICS. Figure height 72 units, from a top of 14 to a baseline of 86,
 * built about the advance axis at x=32.5. Every stroked path in the set is
 * 7 units wide — one weight, one scriber, exponents included. The only filled
 * path in the set is the period's disc, which is filled so that a decimal point
 * cannot disappear under a renderer's butt caps.
 *
 * MONOSPACED. Every text-size glyph advances 65 units and every superscript
 * advances 41.8, so digits stack in a column and a superscript run stays on
 * its own even rhythm. The advance IS the viewBox width — a consumer lays the
 * set out by summing `viewBox[2]`, with no side-table of widths to drift.
 *
 * INK. `inkBounds` is measured by flattening the emitted path strings and
 * sampling them — arc bellies included, stroke width included — never from
 * endpoints or control points. Worst-case overflow past the declared viewBox
 * across the whole set is -2.4 units.
 */

import type { GlyphGeometryId } from "@studio137/plate-core";

import type { LockedPath } from "./types.js";

export const NUMERALS_V1_VERSION = "numerals/v1";

/** The one stroke weight of the set, in viewBox units. */
export const NUMERAL_STROKE_WIDTH = 7;

/** The metric frame every glyph was constructed on. */
export const NUMERAL_METRICS = Object.freeze({
  advance: 65,
  superscriptAdvance: 41.8,
  superscriptScale: 0.6,
  figureTop: 14,
  baseline: 86,
  figureHeight: 72,
  xHeightTop: 36,
  mathAxis: 50,
  strokeWidth: 7,
});

export type NumeralSource = Readonly<{
  id: GlyphGeometryId;
  /** The character this glyph sets. Present so a caller can build a string map. */
  character: string;
  /** How it was constructed, in one sentence. */
  construction: string;
  /** `[minX, minY, width, height]`. The width is also the advance. */
  viewBox: readonly [number, number, number, number];
  paths: readonly LockedPath[];
  /** Measured by sampling the flattened paths, stroke width included. */
  inkBounds: readonly [number, number, number, number];
}>;

const stroke = (d: string): LockedPath =>
  Object.freeze({ d, role: "stroke" as const, strokeWidth: NUMERAL_STROKE_WIDTH });
const fill = (d: string): LockedPath =>
  Object.freeze({ d, role: "fill" as const, strokeWidth: 0 });

const TEXT_VIEWBOX = Object.freeze([0, 0, 65, 100] as const);
const SUPERSCRIPT_VIEWBOX = Object.freeze([0, 0, 41.8, 100] as const);

export const NUMERALS_V1_SOURCE: readonly NumeralSource[] = Object.freeze([
  {
    id: "numeral-0",
    character: "0",
    construction: "four-centre oval, 50 x 72, with an interior slash",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M20.1323 19.1772 A17.3611 17.3611 0 0 1 44.8677 19.1772 A43.92 43.92 0 0 1 44.8677 80.8228 A17.3611 17.3611 0 0 1 20.1323 80.8228 A43.92 43.92 0 0 1 20.1323 19.1772 Z"),
      stroke("M24 62 L41 38"),
    ]),
    inkBounds: Object.freeze([4, 10.5, 61, 89.5] as const),
  },
  {
    id: "numeral-1",
    character: "1",
    construction: "stem, flag, foot serif",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M16 27 L33 14 L33 86"),
      stroke("M17 86 L49 86"),
    ]),
    inkBounds: Object.freeze([12.5, 10.5, 52.5, 89.5] as const),
  },
  {
    id: "numeral-2",
    character: "2",
    construction: "220° bowl, straight diagonal, base bar",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M12.1815 28.8236 A20 20 0 1 1 42.9715 50.383 L10.5 86 L54.5 86"),
    ]),
    inkBounds: Object.freeze([7, 10.5011, 58, 89.5] as const),
  },
  {
    id: "numeral-3",
    character: "3",
    construction: "two crossing circles, r18 over r21",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M14.9532 25.8436 A18 18 0 1 1 42.2169 46.7273 A21 21 0 1 1 12.1341 72.1824"),
    ]),
    inkBounds: Object.freeze([8.6341, 10.501, 56.3658, 89.4962] as const),
  },
  {
    id: "numeral-4",
    character: "4",
    construction: "stem, diagonal, crossbar — one straightedge stroke",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M43.5 86 L43.5 14 L7.5 63 L57.5 63"),
    ]),
    inkBounds: Object.freeze([4, 10.5, 61, 89.5] as const),
  },
  {
    id: "numeral-5",
    character: "5",
    construction: "top bar, stem, 285° bowl",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M50.3764 14 L9.625 14 L9.625 51.8572 A24 24 0 1 1 15.9495 80.3851"),
    ]),
    inkBounds: Object.freeze([6.125, 10.5, 58.875, 89.4928] as const),
  },
  {
    id: "numeral-6",
    character: "6",
    construction: "closed r23 bowl, spine arc struck tangent at nine o'clock",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M51.5 14 A49.5833 49.5833 0 0 0 9.5 63"),
      stroke("M9.5 63 A23 23 0 0 1 55.5 63 A23 23 0 0 1 9.5 63 Z"),
    ]),
    inkBounds: Object.freeze([6, 10.5, 59, 89.5] as const),
  },
  {
    id: "numeral-7",
    character: "7",
    construction: "top bar, diagonal, barred at mid-height",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M8.5 14 L56.5 14 L22.5 86"),
      stroke("M27.5556 52 L49.5556 52"),
    ]),
    inkBounds: Object.freeze([5, 10.5, 60, 89.5] as const),
  },
  {
    id: "numeral-8",
    character: "8",
    construction: "two tangent circles, r16 over r20",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M16.5 30 A16 16 0 0 1 48.5 30 A16 16 0 0 1 16.5 30 Z"),
      stroke("M12.5 66 A20 20 0 0 1 52.5 66 A20 20 0 0 1 12.5 66 Z"),
    ]),
    inkBounds: Object.freeze([9, 10.5, 56, 89.5] as const),
  },
  {
    id: "numeral-9",
    character: "9",
    construction: "the 6, rotated a half-turn about (50, 50)",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M13.5 86 A49.5833 49.5833 0 0 0 55.5 37"),
      stroke("M9.5 37 A23 23 0 0 1 55.5 37 A23 23 0 0 1 9.5 37 Z"),
    ]),
    inkBounds: Object.freeze([6, 10.5, 59, 89.5] as const),
  },
  {
    id: "numeral-plus",
    character: "+",
    construction: "two 40-unit rules crossing on the axis",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M12.5 50 L52.5 50"),
      stroke("M32.5 30 L32.5 70"),
    ]),
    inkBounds: Object.freeze([9, 26.5, 56, 73.5] as const),
  },
  {
    id: "numeral-minus",
    character: "−",
    construction: "the plus's horizontal rule, alone",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M12.5 50 L52.5 50"),
    ]),
    inkBounds: Object.freeze([9, 46.5, 56, 53.5] as const),
  },
  {
    id: "numeral-plusminus",
    character: "±",
    construction: "plus on a raised axis over a base bar",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M15.5 43 L49.5 43"),
      stroke("M32.5 26 L32.5 60"),
      stroke("M15.5 74 L49.5 74"),
    ]),
    inkBounds: Object.freeze([12, 22.5, 53, 77.5] as const),
  },
  {
    id: "numeral-multiply",
    character: "×",
    construction: "the plus at 45°, arms shortened for equal optical mass",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M18.5 36 L46.5 64"),
      stroke("M46.5 36 L18.5 64"),
    ]),
    inkBounds: Object.freeze([15, 32.5, 50, 67.5] as const),
  },
  {
    id: "numeral-period",
    character: ".",
    construction: "filled disc, r4, seated on the baseline ink line",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      fill("M28.5 85.5 A4 4 0 0 1 36.5 85.5 A4 4 0 0 1 28.5 85.5 Z"),
    ]),
    inkBounds: Object.freeze([28.5, 81.5, 36.5, 89.5] as const),
  },
  {
    id: "numeral-solidus",
    character: "/",
    construction: "single rule, overshooting the figure box",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M14.5 88 L50.5 12"),
    ]),
    inkBounds: Object.freeze([11, 8.5, 54, 91.5] as const),
  },
  {
    id: "numeral-paren-left",
    character: "(",
    construction: "arc on an 80-unit chord with a 16-unit sagitta",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M45.5 10 A43.7692 43.7692 0 0 0 45.5 90"),
    ]),
    inkBounds: Object.freeze([16, 6.5, 49, 93.5] as const),
  },
  {
    id: "numeral-paren-right",
    character: ")",
    construction: "the left parenthesis, reflected in the advance axis",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M19.5 10 A43.7692 43.7692 0 0 1 19.5 90"),
    ]),
    inkBounds: Object.freeze([16, 6.5, 49, 93.5] as const),
  },
  {
    id: "numeral-degree",
    character: "°",
    construction: "r7.5 ring at the figure top, 8-unit counter",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M25 25 A7.5 7.5 0 0 1 40 25 A7.5 7.5 0 0 1 25 25 Z"),
    ]),
    inkBounds: Object.freeze([21.5, 14, 43.5, 36] as const),
  },
  {
    id: "numeral-lower-m",
    character: "m",
    construction: "three stems on a 23 pitch, two half-circle arches",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M9.5 86 L9.5 47.5 A11.5 11.5 0 0 1 32.5 47.5 L32.5 86"),
      stroke("M32.5 47.5 A11.5 11.5 0 0 1 55.5 47.5 L55.5 86"),
    ]),
    inkBounds: Object.freeze([6, 32.5, 59, 89.5] as const),
  },
  {
    id: "numeral-cap-l",
    character: "L",
    construction: "stem and foot, centred on the advance",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M14.5 14 L14.5 86 L50.5 86"),
    ]),
    inkBounds: Object.freeze([11, 10.5, 54, 89.5] as const),
  },
  {
    id: "numeral-cap-s",
    character: "S",
    construction: "two equal r18 bowls tangent at the glyph centre, each opened 120° and traced in opposite senses",
    viewBox: TEXT_VIEWBOX,
    paths: Object.freeze([
      stroke("M48.0885 23 A18 18 0 1 0 32.5 50 A18 18 0 1 1 16.9115 77"),
    ]),
    inkBounds: Object.freeze([11, 10.5, 54, 89.5] as const),
  },
  {
    id: "numeral-sup-0",
    character: "⁰",
    construction: "four-centre oval, 50 x 72, with an interior slash — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M13.4794 18.1063 A10.4167 10.4167 0 0 1 28.3206 18.1063 A26.352 26.352 0 0 1 28.3206 55.0937 A10.4167 10.4167 0 0 1 13.4794 55.0937 A26.352 26.352 0 0 1 13.4794 18.1063 Z"),
      stroke("M15.8 43.8 L26 29.4"),
    ]),
    inkBounds: Object.freeze([2.4, 11.5, 39.4, 61.7] as const),
  },
  {
    id: "numeral-sup-1",
    character: "¹",
    construction: "stem, flag, foot serif — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M11 22.8 L21.2 15 L21.2 58.2"),
      stroke("M11.6 58.2 L30.8 58.2"),
    ]),
    inkBounds: Object.freeze([7.5, 11.5, 34.3, 61.7] as const),
  },
  {
    id: "numeral-sup-2",
    character: "²",
    construction: "220° bowl, straight diagonal, base bar — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M8.7089 23.8942 A12 12 0 1 1 27.1829 36.8298 L7.7 58.2 L34.1 58.2"),
    ]),
    inkBounds: Object.freeze([4.2, 11.5007, 37.6, 61.7] as const),
  },
  {
    id: "numeral-sup-3",
    character: "³",
    construction: "two crossing circles, r18 over r21 — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M10.3719 22.1062 A10.8 10.8 0 1 1 26.7301 34.6364 A12.6 12.6 0 1 1 8.6805 49.9095"),
    ]),
    inkBounds: Object.freeze([5.1805, 11.5006, 36.6195, 61.6978] as const),
  },
  {
    id: "numeral-sup-4",
    character: "⁴",
    construction: "stem, diagonal, crossbar — one straightedge stroke — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M27.5 58.2 L27.5 15 L5.9 44.4 L35.9 44.4"),
    ]),
    inkBounds: Object.freeze([2.4, 11.5, 39.4, 61.7] as const),
  },
  {
    id: "numeral-sup-5",
    character: "⁵",
    construction: "top bar, stem, 285° bowl — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M31.6259 15 L7.175 15 L7.175 37.7143 A14.4 14.4 0 1 1 10.9697 54.831"),
    ]),
    inkBounds: Object.freeze([3.675, 11.5, 38.125, 61.6956] as const),
  },
  {
    id: "numeral-sup-6",
    character: "⁶",
    construction: "closed r23 bowl, spine arc struck tangent at nine o'clock — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M32.3 15 A29.75 29.75 0 0 0 7.1 44.4"),
      stroke("M7.1 44.4 A13.8 13.8 0 0 1 34.7 44.4 A13.8 13.8 0 0 1 7.1 44.4 Z"),
    ]),
    inkBounds: Object.freeze([3.6, 11.5, 38.2, 61.7] as const),
  },
  {
    id: "numeral-sup-7",
    character: "⁷",
    construction: "top bar, diagonal, barred at mid-height — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M6.5 15 L35.3 15 L14.9 58.2"),
      stroke("M17.9333 37.8 L31.1333 37.8"),
    ]),
    inkBounds: Object.freeze([3, 11.5, 38.8, 61.7] as const),
  },
  {
    id: "numeral-sup-8",
    character: "⁸",
    construction: "two tangent circles, r16 over r20 — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M11.3 24.6 A9.6 9.6 0 0 1 30.5 24.6 A9.6 9.6 0 0 1 11.3 24.6 Z"),
      stroke("M8.9 46.2 A12 12 0 0 1 32.9 46.2 A12 12 0 0 1 8.9 46.2 Z"),
    ]),
    inkBounds: Object.freeze([5.4, 11.5, 36.4, 61.7] as const),
  },
  {
    id: "numeral-sup-9",
    character: "⁹",
    construction: "the 6, rotated a half-turn about (50, 50) — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M9.5 58.2 A29.75 29.75 0 0 0 34.7 28.8"),
      stroke("M7.1 28.8 A13.8 13.8 0 0 1 34.7 28.8 A13.8 13.8 0 0 1 7.1 28.8 Z"),
    ]),
    inkBounds: Object.freeze([3.6, 11.5, 38.2, 61.7] as const),
  },
  {
    id: "numeral-sup-minus",
    character: "⁻",
    construction: "the plus's horizontal rule, alone — scaled 0.6 onto the superscript grid",
    viewBox: SUPERSCRIPT_VIEWBOX,
    paths: Object.freeze([
      stroke("M8.9 36.6 L32.9 36.6"),
    ]),
    inkBounds: Object.freeze([5.4, 33.1, 36.4, 40.1] as const),
  },
]);

/**
 * Character → glyph id. ASCII `-` is mapped alongside U+2212 MINUS SIGN so a
 * caller typing a plain hyphen still gets the set's minus rather than nothing.
 */
export const NUMERAL_BY_CHARACTER: Readonly<Record<string, GlyphGeometryId>> = Object.freeze({
  "0": "numeral-0",
  "1": "numeral-1",
  "2": "numeral-2",
  "3": "numeral-3",
  "4": "numeral-4",
  "5": "numeral-5",
  "6": "numeral-6",
  "7": "numeral-7",
  "8": "numeral-8",
  "9": "numeral-9",
  "+": "numeral-plus",
  "−": "numeral-minus",
  "±": "numeral-plusminus",
  "×": "numeral-multiply",
  ".": "numeral-period",
  "/": "numeral-solidus",
  "(": "numeral-paren-left",
  ")": "numeral-paren-right",
  "°": "numeral-degree",
  "m": "numeral-lower-m",
  "L": "numeral-cap-l",
  "S": "numeral-cap-s",
  "⁰": "numeral-sup-0",
  "¹": "numeral-sup-1",
  "²": "numeral-sup-2",
  "³": "numeral-sup-3",
  "⁴": "numeral-sup-4",
  "⁵": "numeral-sup-5",
  "⁶": "numeral-sup-6",
  "⁷": "numeral-sup-7",
  "⁸": "numeral-sup-8",
  "⁹": "numeral-sup-9",
  "⁻": "numeral-sup-minus",
  "-": "numeral-minus",
});
