// @ts-nocheck
/* The 201-entry symbol index + tradition metadata. Ported verbatim.
   _seal_* entries are routed to seedSeal() at render time (see Glyph.tsx). */
export type SymbolEntry = {
  n: string; t: string; e: string; m: string;
  g?: string; f?: string; d?: number; id?: string;
};
export type TraditionMeta = Record<string, [string, string]>;

/* ───────── tradition meta ───────── */
const T={
 geo:["Sacred Geometry","--geo"], astro:["Planetary & Astrological","--astro"], alch:["Alchemy","--alch"],
 ang:["Angelic & Theurgic","--ang"], goe:["Goetic & Infernal","--goe"], kab:["Kabbalah & Hebrew","--kab"],
 rune:["Runic & Norse","--rune"], egy:["Egyptian","--egy"], herm:["Hermetic & Universal","--herm"],
 chaos:["Chaos & Modern","--chaos"], ich:["I Ching & Taoist","--ich"], adk:["Adinkra (Akan)","--adk"], vod:["Vodou Veve","--vod"]
};
function U(n,t,e,g,f,m){return{n,t,e,g,f:f||"u-sym",m};}
function G(id,n,t,e,m){return{n,t,e,d:1,id,m};}
function SEAL(id,n,t,e,m){return{n,t,e,d:1,id,m};}

const DATA=[
/* SACRED GEOMETRY */
G("vesica","Vesica Piscis","geo","pre-antiquity","Two circles each through the other's centre — the first division of unity, the womb from which √3 and every later form is generated."),
G("seed","Seed of Life","geo","antiquity","Six circles around a seventh: the days of creation as hexagonal close-packing, the engine of the Flower."),
G("flower","Flower of Life","geo","antiquity","The lattice continued and bounded — overlapping circles read as the blueprint of all proportion."),
G("fruit","Fruit of Life","geo","antiquity","The 13 circles extracted from the Flower; connect their centres and Metatron's Cube appears."),
G("metatron","Metatron's Cube","geo","medieval","All 13 centres joined by all 78 lines — and the five Platonic solids fall out, unasked, inside it."),
G("merkaba","Merkaba / Star Tetrahedron","geo","antiquity","Two interlocked tetrahedra — spirit descending, matter ascending — the counter-rotating light-vehicle."),
G("sriyantra","Sri Yantra","geo","≥1st millennium","Nine interlocking triangles radiating 43 smaller ones around a bindu — a standing wave you can draw, the body of the goddess."),
G("tree","Tree of Life","geo","medieval","Ten emanations joined by 22 paths — the Kabbalistic map of how the infinite condenses into the world."),
G("borromean","Borromean Rings","geo","antiquity","Three rings locked so cutting any one frees the other two — trinity, interdependence, the irreducible knot."),
G("goldenspiral","Golden Spiral","geo","Renaissance","A logarithmic spiral at the ratio φ — growth that keeps its shape at every scale, nautilus to galaxy."),
G("loshu","Lo Shu / Saturn Square","geo","antiquity","The 3×3 magic square, every line summing to 15 — the oldest kamea, ancestor of the planetary seals."),
G("pentagram","Pentagram","geo","antiquity","Five points of the golden ratio — the human microcosm, spirit ruling the four elements when point-up."),
G("hexagram","Hexagram / Seal of Solomon","geo","antiquity","Fire and water, above and below, interlocked — 'as above, so below' as two triangles."),
/* PLANETARY & ASTROLOGICAL */
U("Sun","astro","classical","☉","u-sym","Sol — the self, vitality, the radiant centre; gold among the metals."),
U("Moon","astro","classical","☽","u-sym","Luna — instinct, emotion, the tides of the unconscious; silver."),
U("Mercury","astro","classical","☿","u-sym","Mind, language, exchange, the messenger between worlds; quicksilver."),
U("Venus","astro","classical","♀","u-sym","Love, value, attraction, harmony; copper."),
U("Mars","astro","classical","♂","u-sym","Drive, conflict, courage, the cutting edge; iron."),
U("Jupiter","astro","classical","♃","u-sym","Expansion, fortune, law, benevolence; tin."),
U("Saturn","astro","classical","♄","u-sym","Limit, time, structure, the teacher of hard lessons; lead."),
U("Uranus","astro","modern","♅","u-sym","Disruption, awakening, sudden reversal, the lightning of the new."),
U("Neptune","astro","modern","♆","u-sym","Dissolution, dream, mysticism, the fog that erases edges."),
U("Pluto","astro","modern","♇","u-sym","Death and rebirth, buried power, transformation under pressure."),
U("Earth","astro","classical","🜨","u-sym2","The terrestrial ground — body, manifestation, the cross within the circle."),
U("Aries","astro","classical","♈","u-sym","The ram — cardinal fire, the first spark, raw initiation."),
U("Taurus","astro","classical","♉","u-sym","The bull — fixed earth, the body, what endures and possesses."),
U("Gemini","astro","classical","♊","u-sym","The twins — mutable air, duality, the restless mind."),
U("Cancer","astro","classical","♋","u-sym","The crab — cardinal water, home, the protective shell."),
U("Leo","astro","classical","♌","u-sym","The lion — fixed fire, the radiant ego, sovereignty."),
U("Virgo","astro","classical","♍","u-sym","The maiden — mutable earth, discernment, the sacred craft of refinement."),
U("Libra","astro","classical","♎","u-sym","The scales — cardinal air, balance, relationship, justice."),
U("Scorpio","astro","classical","♏","u-sym","The scorpion — fixed water, depth, death, regeneration."),
U("Sagittarius","astro","classical","♐","u-sym","The archer — mutable fire, the quest, the arrow toward meaning."),
U("Capricorn","astro","classical","♑","u-sym","The sea-goat — cardinal earth, ambition, the long climb."),
U("Aquarius","astro","classical","♒","u-sym","The water-bearer — fixed air, the collective, the future poured out."),
U("Pisces","astro","classical","♓","u-sym","The fishes — mutable water, dissolution, compassion, the dreaming sea."),
U("North Node","astro","classical","☊","u-sym","The dragon's head — the soul's growth-edge, what you're moving toward."),
U("South Node","astro","classical","☋","u-sym","The dragon's tail — past mastery, comfort, what you're releasing."),
U("Conjunction","astro","classical","☌","u-sym","0° — fusion, two forces acting as one."),
U("Opposition","astro","classical","☍","u-sym","180° — tension, the axis of awareness through another."),
U("Retrograde","astro","classical","℞","u-sym","Apparent backward motion — turning inward, review, the inner pass."),
U("Black Moon Lilith","astro","modern","⚸","u-sym2","The lunar apogee — the wild feminine, exile, the un-tamed in the chart."),
/* ALCHEMY */
U("Fire","alch","classical","🜂","u-sym2","Hot and dry — will, transformation, the ascending principle."),
U("Water","alch","classical","🜄","u-sym2","Cold and moist — emotion, dissolution, the descending principle."),
U("Air","alch","classical","🜁","u-sym2","Hot and moist — intellect, the medium, the breath between."),
U("Earth","alch","classical","🜃","u-sym2","Cold and dry — body, fixation, the ground of manifestation."),
U("Sulphur","alch","medieval","🜍","u-sym2","The soul — the combustible, fiery, masculine principle; the consciousness that animates."),
U("Salt","alch","medieval","🜔","u-sym2","The body — the fixed, crystalline, mineral principle; what remains."),
U("Quintessence","alch","medieval","🜀","u-sym2","The fifth element — aether, spirit, the hidden essence drawn from the four."),
U("Gold","alch","medieval","☉","u-sym","Sol — the perfected metal, the goal of the Work, incorruptible."),
U("Silver","alch","medieval","☽","u-sym","Luna — the white, reflective metal of the soul's purification."),
U("Iron","alch","medieval","♂","u-sym","Mars — the warrior metal, blood and force."),
U("Copper","alch","medieval","♀","u-sym","Venus — the green metal of love and verdigris."),
U("Tin","alch","medieval","♃","u-sym","Jupiter — the metal of expansion and benevolent fortune."),
U("Lead","alch","medieval","♄","u-sym","Saturn — the prima materia, the heavy black starting-point of the Work."),
U("Antimony","alch","medieval","♁","u-sym","The wolf of the metals — the feral, devouring agent that purifies gold."),
U("Vitriol","alch","medieval","🜖","u-sym2","V.I.T.R.I.O.L. — 'Visit the interior of the earth; rectifying, you will find the hidden stone.'"),
U("Aqua Vitae","alch","medieval","🜈","u-sym2","The water of life — distilled spirit, the volatile fire-water."),
U("Amalgam","alch","medieval","🜘","u-sym2","The marriage of a metal with mercury — conjunction made literal."),
U("Caput Mortuum","alch","medieval","🜑","u-sym2","The 'dead head' — the residue after distillation; what must be discarded."),
G("ouroboros","Ouroboros","alch","antiquity","The serpent eating its tail — eternal return, the unity of beginning and end, 'the all is one.'"),
G("squaredcircle","Squaring the Circle","alch","medieval","Circle, square, triangle, circle — the emblem of reconciling spirit and matter into the Stone."),
/* ANGELIC & THEURGIC */
G("sigillumdei","Sigillum Dei Aemeth","ang","1582 · Dee","Dee's nested heptagon/heptagram lattice of divine names — the addressing system, drawn as a circuit, for angelic contact."),
SEAL("_seal_Michael_ang","Michael · Sol","ang","Heptameron","Archangel of the Sun — fire, sovereignty, the warrior of light who leads the heavenly host."),
SEAL("_seal_Gabriel_ang","Gabriel · Luna","ang","Heptameron","Archangel of the Moon — the messenger, annunciation, dreams and the waters of the unconscious."),
SEAL("_seal_Raphael_ang","Raphael · Mercury","ang","Heptameron","Archangel of Mercury — healing, travel, the divine physician and teacher of arts."),
SEAL("_seal_Sachiel_ang","Sachiel · Jupiter","ang","Heptameron","Archangel of Jupiter — expansion, mercy, benevolence and lawful increase."),
SEAL("_seal_Cassiel_ang","Cassiel · Saturn","ang","Heptameron","Archangel of Saturn — time, boundary, solitude, the tempering of patience."),
SEAL("_seal_Samael_ang","Samael · Mars","ang","Heptameron","Archangel of Mars — severity, force, the burning blade of judgment."),
SEAL("_seal_Anael_ang","Anael · Venus","ang","Heptameron","Archangel of Venus — love, beauty, harmony and desire."),
SEAL("_seal_Agiel_ang","Agiel · Intelligence of Saturn","ang","Agrippa","The benevolent mind of Saturn, name walked across the 3×3 kamea — discipline made luminous."),
SEAL("_seal_Zazel_goe2","Zazel · Spirit of Saturn","ang","Agrippa","The raw planetary force of Saturn, derived from the Saturn square — the heavy, binding power."),
SEAL("_seal_Iophiel_ang","Iophiel · Intelligence of Jupiter","ang","Agrippa","The mind of Jupiter, walked across the 4×4 Dürer kamea — the beauty of the law."),
SEAL("_seal_Hismael_goe2","Hismael · Spirit of Jupiter","ang","Agrippa","The planetary force of Jupiter, derived from the Jupiter square."),
SEAL("_seal_Graphiel_ang","Graphiel · Intelligence of Mars","ang","Agrippa","The mind of Mars, walked across the 5×5 kamea — focused force."),
SEAL("_seal_Bartzabel_goe2","Bartzabel · Spirit of Mars","ang","Agrippa","The planetary force of Mars, derived from the Mars square — the spirit of war."),
SEAL("_seal_Nakhiel_ang","Nakhiel · Intelligence of the Sun","ang","Agrippa","The solar mind, walked across the 6×6 kamea — the intelligence of light."),
SEAL("_seal_Sorath_goe2","Sorath · Spirit of the Sun","ang","Agrippa","The solar daemon (number 666), the raw force of the Sun's square."),
SEAL("_seal_Hagiel_ang","Hagiel · Intelligence of Venus","ang","Agrippa","The Venusian mind, walked across the 7×7 kamea — intelligent harmony."),
SEAL("_seal_Kedemel_goe2","Kedemel · Spirit of Venus","ang","Agrippa","The planetary force of Venus, derived from the Venus square."),
SEAL("_seal_Tiriel_ang","Tiriel · Intelligence of Mercury","ang","Agrippa","The Mercurial mind, walked across the 8×8 kamea — quicksilver intellect."),
SEAL("_seal_Taph_goe2","Taphthartharath · Spirit of Mercury","ang","Agrippa","The planetary force of Mercury, derived from the Mercury square."),
SEAL("_seal_Aratron_olym","Aratron · Olympic Spirit of Saturn","ang","Arbatel 1575","Governor of 49 provinces — teaches alchemy and invisibility, turns the living to stone, confers long life."),
SEAL("_seal_Bethor_olym","Bethor · Olympic Spirit of Jupiter","ang","Arbatel 1575","Governor of 42 provinces — answers swiftly, raises to high office, opens hidden treasure."),
SEAL("_seal_Phaleg_olym","Phaleg · Olympic Spirit of Mars","ang","Arbatel 1575","Governor of 35 provinces — the War-Lord, granter of martial honour."),
SEAL("_seal_Och_olym","Och · Olympic Spirit of the Sun","ang","Arbatel 1575","Governor of 28 provinces — the alchemist-physician, perfects gold and grants 600 years of health."),
SEAL("_seal_Hagith_olym","Hagith · Olympic Spirit of Venus","ang","Arbatel 1575","Governor of 21 provinces — transmuter of metals, bestower of beauty and faithful familiars."),
SEAL("_seal_Ophiel_olym","Ophiel · Olympic Spirit of Mercury","ang","Arbatel 1575","Governor of 14 provinces — teaches all arts, turns quicksilver into the Philosopher's Stone."),
SEAL("_seal_Phul_olym","Phul · Olympic Spirit of the Moon","ang","Arbatel 1575","Governor of 7 provinces — transmutes all metals to silver, heals, commands the spirits of water."),
/* GOETIC & INFERNAL */
G("baphomet","Sigil of Baphomet","goe","modern","Inverted pentagram in two circles, the five points lettered LVITN — Leviathan — the Sabbatic Goat as emblem of matter and the lower will."),
G("leviathancross","Leviathan Cross","goe","medieval","The Cross of Sulphur / brimstone — a double cross over the infinity loop, the alchemical 'fire' adopted as a sign of the abyss."),
G("lucifersigil","Sigil of Lucifer","goe","18th c.","From the Grimorium Verum — the 'light-bringer' rendered as an abstract seal of chalice, staff and crossing paths."),
SEAL("_seal_Bael_goe","Bael","goe","Lemegeton","First king of the 72 — grants invisibility and wisdom; appears with the heads of cat, toad and man."),
SEAL("_seal_Paimon_goe","Paimon","goe","Lemegeton","A great king who teaches all arts, sciences and secrets; comes with a host and great noise."),
SEAL("_seal_Asmoday_goe","Asmoday","goe","Lemegeton","King of the 72 — teaches mathematics and the powers of treasure; guardian of hidden things."),
SEAL("_seal_Belial_goe","Belial","goe","Lemegeton","A mighty king of lawlessness — grants favour, senatorships and the loyalty of friends and foes."),
SEAL("_seal_Astaroth_goe","Astaroth","goe","Lemegeton","A great duke — reveals the past and future and the secrets of the fall of spirits."),
SEAL("_seal_Bune_goe","Bune","goe","Lemegeton","A duke who moves the dead and grants riches, wisdom and eloquence."),
SEAL("_seal_Stolas_goe","Stolas","goe","Lemegeton","A prince in the form of a crowned owl — teaches astronomy and the virtues of herbs and stones."),
SEAL("_seal_Andromalius_goe","Andromalius","goe","Lemegeton","The 72nd earl — returns stolen goods, exposes thieves and wickedness, punishes the deceitful."),
SEAL("_seal_Vassago_goe","Vassago","goe","Lemegeton","A benign prince — declares things past and to come, finds what is lost or hidden."),
/* KABBALAH & HEBREW */
U("Aleph · א","kab","ancient","א","u-heb","Value 1 — the ox, breath, the silent unity before sound; the Fool of the Tarot."),
U("Bet · ב","kab","ancient","ב","u-heb","Value 2 — the house, the container, the first duality; the Magus."),
U("Gimel · ג","kab","ancient","ג","u-heb","Value 3 — the camel crossing the desert between the supernals; the High Priestess."),
U("Dalet · ד","kab","ancient","ד","u-heb","Value 4 — the door, the threshold; the Empress."),
U("He · ה","kab","ancient","ה","u-heb","Value 5 — the window, breath, revelation; the Emperor."),
U("Vav · ו","kab","ancient","ו","u-heb","Value 6 — the nail that joins heaven and earth; the Hierophant."),
U("Zayin · ז","kab","ancient","ז","u-heb","Value 7 — the sword, discrimination; the Lovers."),
U("Chet · ח","kab","ancient","ח","u-heb","Value 8 — the fence, the field of the heart; the Chariot."),
U("Tet · ט","kab","ancient","ט","u-heb","Value 9 — the serpent coiled, hidden good; Strength / Lust."),
U("Yod · י","kab","ancient","י","u-heb","Value 10 — the hand, the seed-point from which all letters spring; the Hermit."),
U("Kaf · כ","kab","ancient","כ","u-heb","Value 20 — the open palm, grasping; the Wheel of Fortune."),
U("Lamed · ל","kab","ancient","ל","u-heb","Value 30 — the ox-goad, teaching and aspiration; Justice."),
U("Mem · מ","kab","ancient","מ","u-heb","Value 40 — the waters, the great deep; the Hanged Man."),
U("Nun · נ","kab","ancient","נ","u-heb","Value 50 — the fish in the waters, death and regeneration; Death."),
U("Samekh · ס","kab","ancient","ס","u-heb","Value 60 — the prop, the supporting circle; Temperance / Art."),
U("Ayin · ע","kab","ancient","ע","u-heb","Value 70 — the eye, perception and its illusions; the Devil."),
U("Pe · פ","kab","ancient","פ","u-heb","Value 80 — the mouth, speech that shatters; the Tower."),
U("Tsadi · צ","kab","ancient","צ","u-heb","Value 90 — the fish-hook that draws up; the Star."),
U("Qof · ק","kab","ancient","ק","u-heb","Value 100 — the back of the head, the dreaming sleep; the Moon."),
U("Resh · ר","kab","ancient","ר","u-heb","Value 200 — the head, the face of consciousness; the Sun."),
U("Shin · ש","kab","ancient","ש","u-heb","Value 300 — the tooth, the threefold flame of spirit; Judgement / the Aeon."),
U("Tav · ת","kab","ancient","ת","u-heb","Value 400 — the cross/mark, completion, the seal on all things; the Universe."),
U("Tetragrammaton","kab","ancient","יהוה","u-heb","The unspoken four-letter Name — the formula of the whole, read but never pronounced."),
/* RUNIC & NORSE */
U("Fehu · ᚠ","rune","Elder Futhark","ᚠ","u-runic","Cattle, wealth — mobile abundance, energy that must circulate or rot."),
U("Uruz · ᚢ","rune","Elder Futhark","ᚢ","u-runic","The aurochs — primal strength, vitality, the untamed shaping force."),
U("Thurisaz · ᚦ","rune","Elder Futhark","ᚦ","u-runic","The thorn / giant — reactive force, defence, the hammer of Thor."),
U("Ansuz · ᚨ","rune","Elder Futhark","ᚨ","u-runic","The god, Odin's breath — speech, inspiration, the word that orders."),
U("Raidho · ᚱ","rune","Elder Futhark","ᚱ","u-runic","The ride, the journey — right motion, rhythm, the wheel of the path."),
U("Kenaz · ᚲ","rune","Elder Futhark","ᚲ","u-runic","The torch — controlled fire, knowledge, the craft that reveals."),
U("Gebo · ᚷ","rune","Elder Futhark","ᚷ","u-runic","The gift — exchange, the sacred bond, the X of giving and receiving."),
U("Wunjo · ᚹ","rune","Elder Futhark","ᚹ","u-runic","Joy — harmony, fulfilment, the kinship of things in accord."),
U("Hagalaz · ᚺ","rune","Elder Futhark","ᚺ","u-runic","Hail — disruption, the destructive seed, crisis that reorders."),
U("Nauthiz · ᚾ","rune","Elder Futhark","ᚾ","u-runic","Need — constraint, the friction-fire, necessity as teacher."),
U("Isa · ᛁ","rune","Elder Futhark","ᛁ","u-runic","Ice — stillness, stasis, the frozen single will."),
U("Jera · ᛃ","rune","Elder Futhark","ᛃ","u-runic","Year, harvest — cycles, the reward of right timing, the turning seasons."),
U("Eihwaz · ᛇ","rune","Elder Futhark","ᛇ","u-runic","The yew — the world-axis, life and death, the spine between worlds."),
U("Perthro · ᛈ","rune","Elder Futhark","ᛈ","u-runic","The lot-cup — fate, chance, mystery, the dice of the Norns."),
U("Algiz · ᛉ","rune","Elder Futhark","ᛉ","u-runic","The elk, the warding hand — protection, the bridge to the higher self."),
U("Sowilo · ᛊ","rune","Elder Futhark","ᛊ","u-runic","The sun — victory, the guiding light, the wholeness of will."),
U("Tiwaz · ᛏ","rune","Elder Futhark","ᛏ","u-runic","Tyr — justice, sacrifice, the spear of honour pointing true."),
U("Berkano · ᛒ","rune","Elder Futhark","ᛒ","u-runic","The birch — birth, growth, the nurturing feminine, new beginnings."),
U("Ehwaz · ᛖ","rune","Elder Futhark","ᛖ","u-runic","The horse — partnership, trust, the harmonious pair in motion."),
U("Mannaz · ᛗ","rune","Elder Futhark","ᛗ","u-runic","Humankind — the self, intelligence, the social and divine in one."),
U("Laguz · ᛚ","rune","Elder Futhark","ᛚ","u-runic","Water, lake — flow, the unconscious, intuition and life-energy."),
U("Ingwaz · ᛜ","rune","Elder Futhark","ᛜ","u-runic","Ing — the stored seed, gestation, potential held until release."),
U("Dagaz · ᛞ","rune","Elder Futhark","ᛞ","u-runic","Day — dawn, breakthrough, the threshold between dark and light."),
U("Othala · ᛟ","rune","Elder Futhark","ᛟ","u-runic","The ancestral homeland — heritage, the inheritance you guard and pass on."),
G("vegvisir","Vegvísir","rune","Huld MS 1847","The Icelandic wayfinder — eight staved arms in a wheel so the bearer 'will not lose their way in storms.'"),
G("aegishjalmur","Ægishjálmur · Helm of Awe","rune","Galdrabók 17c.","Eight Algiz-armed tridents radiating from a centre — worn between the eyes to instil terror and ward the self."),
G("veldismagn","Veldismagn","rune","galdrastafir","Eight spokes meeting at a point — 'to give power and strength,' carried for protection and safe return."),
G("valknut","Valknut","rune","Norse","Three interlocked triangles — the knot of the slain, Odin's binding of the mind between worlds."),
G("webofwyrd","Web of Wyrd","rune","Norse","Nine staves woven into a matrix — the loom of fate, every line a thread of past, present and becoming."),
/* EGYPTIAN */
U("Ankh","egy","Old Kingdom","☥","u-sym","The key of life — the union of male and female principles, breath and eternity held in a loop."),
G("eyehorus","Eye of Horus · Wedjat","egy","Old Kingdom","The restored eye — healing, protection, royal power; its parts encode the fractions of perception."),
U("Eye of Ra · 𓁹","egy","Old Kingdom","𓁹","u-hiero","The solar eye — the burning, protective, feminine fury of the sun-god."),
U("Djed · 𓊽","egy","Old Kingdom","𓊽","u-hiero","The backbone of Osiris — stability, endurance, the pillar that raises the world upright."),
U("Was · 𓌀","egy","Old Kingdom","𓌀","u-hiero","The was-sceptre — dominion, the power of the gods to uphold order."),
U("Scarab · 𓆣","egy","Old Kingdom","𓆣","u-hiero","Khepri's beetle — becoming, the self-renewing sun rolled up each dawn from nothing."),
U("Feather of Maat · 𓆄","egy","Old Kingdom","𓆄","u-hiero","The ostrich feather against which the heart is weighed — truth, balance, cosmic order."),
U("Nefer · 𓄤","egy","Old Kingdom","𓄤","u-hiero","Beauty, goodness, perfection — the heart-and-windpipe sign of all that is well-made."),
U("Sun · 𓇳","egy","Old Kingdom","𓇳","u-hiero","Ra — the disc, the source, the daily death and resurrection of light."),
G("tyet","Tyet · Knot of Isis","egy","Old Kingdom","The blood-knot of Isis — protection of the goddess, the girdle that guards the living and the dead."),
G("akhet","Akhet · Horizon","egy","Old Kingdom","The sun between two peaks — the horizon of becoming, the gate of dawn and the afterlife."),
G("sa","Sa · Protection","egy","Old Kingdom","The rolled herdsman's shelter — the hieroglyph for magical protection itself."),
/* HERMETIC & UNIVERSAL */
G("monas","Monas Hieroglyphica","herm","1564 · Dee","One composite character — moon, sun, cross and Aries stacked — Dee's claim to encode the unity of the cosmos."),
G("rosecross","Rose Cross","herm","Rosicrucian","The rose blooming at the heart of the cross — matter and spirit, sacrifice and unfolding consciousness."),
G("unicursalhex","Unicursal Hexagram","herm","Thelema","The six-pointed star drawn in one stroke — the macrocosm traced without lifting the pen, the rose at centre."),
G("eyeprov","Eye of Providence","herm","Renaissance","The all-seeing eye in the radiant triangle — divine omniscience watching over the manifest world."),
G("triquetra","Triquetra","herm","Celtic","Three interlocked vesicas — the trinity, the three realms, the eternal woven without beginning."),
G("triskele","Triskelion","herm","antiquity","Three spiralling legs — motion, progress, the triple turning of life, death and rebirth."),
G("triplemoon","Triple Moon","herm","modern","Waxing, full and waning — Maiden, Mother and Crone, the threefold goddess and the lunar cycle."),
G("hecate","Hecate's Wheel · Strophalos","herm","Greek","The triple labyrinth of the crossroads-goddess — her three faces guarding the ways between worlds."),
G("hamsa","Hamsa","herm","Near East","The protective hand with the eye in its palm — warding the evil eye, the open hand of blessing."),
U("Yin-Yang","herm","Taoist","☯","u-sym","The Taijitu — the dynamic balance of complements, each carrying the seed of the other."),
U("Pentacle","herm","modern","⛤","u-sym2","The encircled pentagram — spirit crowning the four elements, bound in the wheel of protection."),
U("Caduceus","herm","Greek","☤","u-sym","Twin serpents on the winged staff of Hermes — exchange, the reconciliation of opposites."),
U("Chi-Rho","herm","late antiquity","☧","u-sym","The first letters of Christos — Constantine's labarum, the conquering monogram."),
/* CHAOS & MODERN */
G("chaosstar","Chaos Star","chaos","1970s","Eight arrows radiating in every direction — the Symbol of Chaos, all possibilities, belief as a tool."),
G("chaossphere","Chaosphere","chaos","modern","The chaos star wrapped onto a sphere — a three-dimensional focus for the magician's intent."),
/* I CHING & TAOIST */
U("Qián · ☰","ich","Zhou","☰","u-sym","Heaven — the Creative, pure yang, the originating force."),
U("Duì · ☱","ich","Zhou","☱","u-sym","Lake — the Joyous, openness, pleasure, the still water."),
U("Lí · ☲","ich","Zhou","☲","u-sym","Fire — the Clinging, clarity, that which depends and illuminates."),
U("Zhèn · ☳","ich","Zhou","☳","u-sym","Thunder — the Arousing, shock, the sudden movement that wakes."),
U("Xùn · ☴","ich","Zhou","☴","u-sym","Wind / Wood — the Gentle, penetration, persistent quiet influence."),
U("Kǎn · ☵","ich","Zhou","☵","u-sym","Water — the Abysmal, danger, the flowing depth one must move through."),
U("Gèn · ☶","ich","Zhou","☶","u-sym","Mountain — Keeping Still, stillness, the limit, meditation."),
U("Kūn · ☷","ich","Zhou","☷","u-sym","Earth — the Receptive, pure yin, the yielding that sustains."),
U("Hexagram 1 · ䷀","ich","Zhou","䷀","u-sym2","Qián, the Creative doubled — heaven upon heaven, pure initiating power."),
U("Hexagram 2 · ䷁","ich","Zhou","䷁","u-sym2","Kūn, the Receptive doubled — earth upon earth, total devoted yielding."),
/* ADINKRA */
G("gyenyame","Gye Nyame","adk","Akan","'Except for God' — the supremacy and omnipotence of the divine; the most beloved Adinkra symbol."),
G("sankofa","Sankofa","adk","Akan","'Go back and fetch it' — the wisdom of learning from the past to build the future."),
G("adinkrahene","Adinkrahene","adk","Akan","Concentric circles — greatness, charisma, leadership; the chief of all Adinkra symbols."),
G("dwennimmen","Dwennimmen","adk","Akan","Ram's horns — strength tempered by humility; even the strong submit when they must."),
G("akoma","Akoma","adk","Akan","The heart — patience, tolerance, endurance; 'take heart,' the long-suffering of love."),
G("eban","Eban","adk","Akan","The fence — security, safety, the love whose boundary protects the home."),
G("nkyinkyim","Nkyinkyim","adk","Akan","The twisting — dynamism, adaptability, the winding initiative of a life well-navigated."),
/* VODOU VEVE */
G("damballa","Damballa Wedo","vod","Vodou","The great serpent-lwa — two snakes flanking the world-pillar; creation, purity, the cosmic life-force."),
G("legba","Papa Legba","vod","Vodou","Keeper of the crossroads — the gate between humanity and the lwa; nothing passes without him first."),
G("erzulie","Erzulie Freda","vod","Vodou","The lwa of love and beauty — the ornate heart, luxury, the sweetness and sorrow of desire."),
G("baronsamedi","Baron Samedi","vod","Vodou","Master of the dead and the cemetery — the cross of the Gede, guardian of the threshold of death.")
];

export { T as TRADITIONS, DATA };
