/**
 * Regenerate the golden fixture's release-gate hashes (spec §29).
 *
 *   pnpm golden:hash
 *
 * These become permanent release gates: the AST hash, presentation hash, SVG
 * hash, print hash, and PNG pixel hash of `THE SIGNAL SURVIVES THE BODY`.
 * Regenerating them is a deliberate act that says "the artwork this fixture
 * produces has intentionally changed" — never a way to quiet a failing test.
 */

import { writeFileSync } from "node:fs";

import { canonicalDigest } from "@studio137/plate-core";
import { compilePlate, exportProductionPng, exportPublic } from "@studio137/plate-compiler";
import { RASTERIZER } from "@studio137/render-raster";

import { GOLDEN_REQUEST } from "../apps/cli/src/golden.js";

const plate = compilePlate(GOLDEN_REQUEST);
const published = exportPublic(plate);
// Rasterize small: the pixel hash is a determinism check, not a proof sheet.
const raster = exportProductionPng(plate, published.canonicalSvg, {
  widthPx: 600,
  background: "#ffffff",
});

const fixture = {
  note:
    "Generated by `pnpm golden:hash`. Permanent release gates for the golden " +
    "fixture (spec §29). The PNG hash is pinned to the rasterizer named below.",
  phrase: GOLDEN_REQUEST.phrase,
  seed: GOLDEN_REQUEST.seed,
  plateId: plate.plateId,
  requestDigest: plate.requestDigest,
  astSha256: canonicalDigest(plate.ast),
  presentationSha256: canonicalDigest(plate.presentation),
  canonicalSvgSha256: published.canonicalSvgSha256,
  printSvgSha256: published.printSvgSha256,
  canonicalPathDigest: published.canonicalPathDigest,
  rasterizer: RASTERIZER,
  productionPngWidthPx: raster.widthPx,
  productionPngSha256: raster.sha256,
  clauseSheetReading: plate.analysis.clauses.map((clause) => clause.reading),
  minimumStrokePt: plate.presentation.layout.minimumStrokePt,
};

const target = new URL("../tests/fixtures/golden-hashes.json", import.meta.url);
writeFileSync(target, `${JSON.stringify(fixture, null, 2)}\n`, "utf8");
process.stdout.write(`Wrote golden release gates for plate ${plate.plateId}\n`);
process.stdout.write(`  ast    ${fixture.astSha256}\n`);
process.stdout.write(`  svg    ${fixture.canonicalSvgSha256}\n`);
process.stdout.write(`  png    ${fixture.productionPngSha256}\n`);
